import 'package:solosoul_flutter/gen/l10n/app_localizations.dart';

/// 将字段 key（camelCase / snake_case）格式化为人类可读的 Title Case。
///
/// 例如：
/// - "givenName" → "Given Name"
/// - "dateOfBirth" → "Date Of Birth"
/// - "visa_type" → "Visa Type"
String formatFieldLabel(String key) {
  final spaced = key.replaceAllMapped(
    RegExp(r'([a-z])([A-Z])'),
    (m) => '${m[1]} ${m[2]}',
  );
  return spaced.replaceAll('_', ' ').split(' ').map((word) {
    if (word.isEmpty) return word;
    return word[0].toUpperCase() + word.substring(1).toLowerCase();
  }).join(' ');
}

/// Translate a field key using l10n, falling back to [formatFieldLabel]
/// for unknown keys (e.g. user-defined custom fields).
String translateFieldLabel(String key, AppLocalizations l10n) {
  return switch (key) {
    'fullName' => l10n.fieldFullName,
    'givenName' => l10n.fieldGivenName,
    'familyName' => l10n.fieldFamilyName,
    'dateOfBirth' => l10n.fieldDateOfBirth,
    'gender' => l10n.fieldGender,
    'nationality' => l10n.fieldNationality,
    'title' => l10n.fieldTitle,
    'Title' => l10n.fieldTitle,
    'type' => l10n.fieldType,
    'value' => l10n.fieldValue,
    'number' => l10n.fieldNumber,
    'issueDate' => l10n.fieldIssueDate,
    'expiryDate' => l10n.fieldExpiryDate,
    'holderName' => l10n.fieldHolderName,
    'country' => l10n.fieldCountry,
    'street' => l10n.fieldStreet,
    'city' => l10n.fieldCity,
    'district' => l10n.fieldDistrict,
    'state' => l10n.fieldState,
    'postalCode' => l10n.fieldPostalCode,
    'passportNumber' => l10n.fieldPassportNumber,
    'issuingCountry' => l10n.fieldIssuingCountry,
    'visaNumber' => l10n.fieldVisaNumber,
    'entryDate' => l10n.fieldEntryDate,
    'exitDate' => l10n.fieldExitDate,
    'bankName' => l10n.fieldBankName,
    'bank_name' => l10n.fieldBankName,
    'accountNumber' => l10n.fieldAccountNumber,
    'account_number' => l10n.fieldAccountNumber,
    'accountHolder' => l10n.fieldAccountHolder,
    'account_holder' => l10n.fieldAccountHolder,
    'swiftCode' => l10n.fieldSwiftCode,
    'iban' => l10n.fieldIban,
    'cardNumber' => l10n.fieldCardNumber,
    'cardholderName' => l10n.fieldCardholderName,
    'cvv' => l10n.fieldCvv,
    'taxIdNumber' => l10n.fieldTaxIdNumber,
    'institution' => l10n.fieldInstitution,
    'degree' => l10n.fieldDegree,
    'fieldOfStudy' => l10n.fieldFieldOfStudy,
    'startDate' => l10n.fieldStartDate,
    'endDate' => l10n.fieldEndDate,
    'company' => l10n.fieldCompany,
    'position' => l10n.fieldPosition,
    'category' => l10n.fieldCategory,
    'level' => l10n.fieldLevel,
    'language' => l10n.fieldLanguage,
    'proficiency' => l10n.fieldProficiency,
    'organization' => l10n.fieldOrganization,
    'phone' => l10n.fieldPhone,
    'email' => l10n.fieldEmail,
    'content' => l10n.fieldContent,
    'countryCode' => l10n.fieldCountryCode,
    'placeOfIssue' => l10n.fieldPlaceOfIssue,
    'placeOfBirth' => l10n.fieldPlaceOfBirth,
    'sex' => l10n.fieldSex,
    'authority' => l10n.fieldAuthority,
    'visaType' => l10n.fieldVisaType,
    'destination' => l10n.fieldDestination,
    'travelType' => l10n.fieldTravelType,
    'departureCity' => l10n.fieldDepartureCity,
    'departureTime' => l10n.fieldDepartureTime,
    'arrivalTime' => l10n.fieldArrivalTime,
    'flightNumber' => l10n.fieldFlightNumber,
    'ticketPrice' => l10n.fieldTicketPrice,
    'airline' => l10n.fieldAirline,
    'currency' => l10n.fieldCurrency,
    'swiftBic' => l10n.fieldSwiftBic,
    'sortCode' => l10n.fieldSortCode,
    'sort_code' => l10n.fieldSortCode,
    'routingNumber' => l10n.fieldRoutingNumber,
    'routing_number' => l10n.fieldRoutingNumber,
    'accountType' => l10n.fieldAccountType,
    'account_type' => l10n.fieldAccountType,
    'branchName' => l10n.fieldBranchName,
    'branch_name' => l10n.fieldBranchName,
    'cardType' => l10n.fieldCardType,
    'taxIdType' => l10n.fieldTaxIdType,
    'issuingAuthority' => l10n.fieldIssuingAuthority,
    'degreeCustom' => l10n.fieldDegreeCustom,
    'field' => l10n.fieldField,
    'responsibilities' => l10n.fieldResponsibilities,
    'issuer' => l10n.fieldIssuer,
    'description' => l10n.fieldDescription,
    'name' => l10n.fieldName,
    'authors' => l10n.fieldAuthors,
    'contact' => l10n.fieldContactInfo,
    'abstract' => l10n.fieldAbstract,
    'doi' => l10n.fieldDoi,
    'url' => l10n.fieldUrl,
    'venue' => l10n.fieldVenue,
    'year' => l10n.fieldYear,
    'citation' => l10n.fieldCitation,
    'done' => l10n.fieldDone,
    'dueDate' => l10n.fieldDueDate,
    // Snake case variants (used by section templates)
    'full_name' => l10n.fieldFullName,
    'given_name' => l10n.fieldGivenName,
    'family_name' => l10n.fieldFamilyName,
    'date_of_birth' => l10n.fieldDateOfBirth,
    'issue_date' => l10n.fieldIssueDate,
    'expiry_date' => l10n.fieldExpiryDate,
    'holder_name' => l10n.fieldHolderName,
    'card_number' => l10n.fieldCardNumber,
    'card_type' => l10n.fieldCardType,
    'country_code' => l10n.fieldCountryCode,
    'postal_code' => l10n.fieldPostalCode,
    'issuing_authority' => l10n.fieldIssuingAuthority,
    'place_of_issue' => l10n.fieldPlaceOfIssue,
    'place_of_birth' => l10n.fieldPlaceOfBirth,
    'tax_id_number' => l10n.fieldTaxIdNumber,
    'tax_id_type' => l10n.fieldTaxIdType,
    'visa_type' => l10n.fieldVisaType,
    'travel_type' => l10n.fieldTravelType,
    'departure_city' => l10n.fieldDepartureCity,
    'departure_time' => l10n.fieldDepartureTime,
    'arrival_time' => l10n.fieldArrivalTime,
    'flight_number' => l10n.fieldFlightNumber,
    'ticket_price' => l10n.fieldTicketPrice,
    'date' => l10n.fieldDate,
    _ => formatFieldLabel(key),
  };
}
