// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SoloHostFunctions>>
abstract class SoloHostFunctions implements RustOpaqueInterface {
  /// Get email (requires confirmation)
  Future<String> getEmail();

  /// Get ID card number (requires strict confirmation + TTL)
  Future<String> getIdCardNumber();

  /// Get phone number (requires confirmation)
  Future<String> getPhone();

  /// Get user name (requires confirmation)
  Future<String> getUserName();

  /// Check if field is allowed
  Future<bool> isFieldAllowed({required String field});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create new host functions
  static Future<SoloHostFunctions> newInstance({
    required String pluginId,
    required String sessionId,
    required List<String> requestedFields,
  }) => RustLib.instance.api.cratePluginHostSoloHostFunctionsNew(
    pluginId: pluginId,
    sessionId: sessionId,
    requestedFields: requestedFields,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Trap>>
abstract class Trap implements RustOpaqueInterface {}

/// Host functions for plugin access
class SoloHostFunctions {
  /// Plugin ID
  final String pluginId;

  /// Session ID for audit
  final String sessionId;

  /// Requested fields (from manifest)
  final List<String> requestedFields;

  const SoloHostFunctions({
    required this.pluginId,
    required this.sessionId,
    required this.requestedFields,
  });

  /// Get email (requires confirmation)
  Future<String> getEmail() =>
      RustLib.instance.api.cratePluginHostSoloHostFunctionsGetEmail(that: this);

  /// Get ID card number (requires strict confirmation + TTL)
  Future<String> getIdCardNumber() => RustLib.instance.api
      .cratePluginHostSoloHostFunctionsGetIdCardNumber(that: this);

  /// Get phone number (requires confirmation)
  Future<String> getPhone() =>
      RustLib.instance.api.cratePluginHostSoloHostFunctionsGetPhone(that: this);

  /// Get user name (requires confirmation)
  Future<String> getUserName() => RustLib.instance.api
      .cratePluginHostSoloHostFunctionsGetUserName(that: this);

  /// Check if field is allowed
  Future<bool> isFieldAllowed({required String field}) => RustLib.instance.api
      .cratePluginHostSoloHostFunctionsIsFieldAllowed(that: this, field: field);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create new host functions
  static Future<SoloHostFunctions> newInstance({
    required String pluginId,
    required String sessionId,
    required List<String> requestedFields,
  }) => RustLib.instance.api.cratePluginHostSoloHostFunctionsNew(
    pluginId: pluginId,
    sessionId: sessionId,
    requestedFields: requestedFields,
  );

  @override
  int get hashCode =>
      pluginId.hashCode ^ sessionId.hashCode ^ requestedFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoloHostFunctions &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          sessionId == other.sessionId &&
          requestedFields == other.requestedFields;
}
