// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'manager.freezed.dart';

@freezed
sealed class PluginEvent with _$PluginEvent {
  const PluginEvent._();

  const factory PluginEvent.consentRequest({
    required String requestId,
    required String pluginId,
    required String pluginName,
    required String field,
    required String sensitivity,
  }) = PluginEvent_ConsentRequest;
  const factory PluginEvent.consentTimeout({required String requestId}) =
      PluginEvent_ConsentTimeout;
  const factory PluginEvent.log({
    required String level,
    required String message,
  }) = PluginEvent_Log;
  const factory PluginEvent.progress({required int percent}) =
      PluginEvent_Progress;
  const factory PluginEvent.completed({required int exitCode}) =
      PluginEvent_Completed;
  const factory PluginEvent.error({required String message}) =
      PluginEvent_Error;
}
