// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_block_all_outbound`, `default_require_user_confirmation`, `field_matches`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Network policy for plugin
class NetworkPolicy {
  final List<String> allowedDomains;
  final bool blockAllOutbound;

  const NetworkPolicy({
    required this.allowedDomains,
    required this.blockAllOutbound,
  });

  @override
  int get hashCode => allowedDomains.hashCode ^ blockAllOutbound.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkPolicy &&
          runtimeType == other.runtimeType &&
          allowedDomains == other.allowedDomains &&
          blockAllOutbound == other.blockAllOutbound;
}

/// Plugin manifest (manifest.json)
class PluginManifest {
  final String pluginId;
  final String name;
  final String version;
  final List<String> requiredFields;
  final List<String> optionalFields;
  final NetworkPolicy? networkPolicy;
  final BigInt dataTtlSeconds;
  final bool requireUserConfirmation;

  const PluginManifest({
    required this.pluginId,
    required this.name,
    required this.version,
    required this.requiredFields,
    required this.optionalFields,
    this.networkPolicy,
    required this.dataTtlSeconds,
    required this.requireUserConfirmation,
  });

  /// Check if a field is requested
  Future<bool> isFieldRequested({required String field}) =>
      RustLib.instance.api.cratePluginManifestPluginManifestIsFieldRequested(
        that: this,
        field: field,
      );

  /// Validate manifest
  Future<void> validate() => RustLib.instance.api
      .cratePluginManifestPluginManifestValidate(that: this);

  @override
  int get hashCode =>
      pluginId.hashCode ^
      name.hashCode ^
      version.hashCode ^
      requiredFields.hashCode ^
      optionalFields.hashCode ^
      networkPolicy.hashCode ^
      dataTtlSeconds.hashCode ^
      requireUserConfirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginManifest &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          name == other.name &&
          version == other.version &&
          requiredFields == other.requiredFields &&
          optionalFields == other.optionalFields &&
          networkPolicy == other.networkPolicy &&
          dataTtlSeconds == other.dataTtlSeconds &&
          requireUserConfirmation == other.requireUserConfirmation;
}
