// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Network policy for plugin
class NetworkPolicy {
  final List<String> allowedDomains;
  final bool blockAllOutbound;

  const NetworkPolicy({
    required this.allowedDomains,
    required this.blockAllOutbound,
  });

  @override
  int get hashCode => allowedDomains.hashCode ^ blockAllOutbound.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkPolicy &&
          runtimeType == other.runtimeType &&
          allowedDomains == other.allowedDomains &&
          blockAllOutbound == other.blockAllOutbound;
}

/// Plugin manifest (manifest.json)
class PluginManifest {
  final String pluginId;
  final String name;
  final String version;

  /// 插件 ABI 版本，与主软件严格匹配
  final String pluginApiVersion;

  /// 兼容的最低 SoloSoul App 版本
  final String minAppVersion;

  /// 兼容的最高 SoloSoul App 版本
  final String maxAppVersion;
  final String description;
  final String publisher;
  final String? homepage;
  final String? signature;
  final List<String> requiredFields;
  final List<String> optionalFields;
  final NetworkPolicy? networkPolicy;
  final BigInt dataTtlSeconds;
  final bool requireUserConfirmation;
  final BigInt consentValidityHours;

  const PluginManifest({
    required this.pluginId,
    required this.name,
    required this.version,
    required this.pluginApiVersion,
    required this.minAppVersion,
    required this.maxAppVersion,
    required this.description,
    required this.publisher,
    this.homepage,
    this.signature,
    required this.requiredFields,
    required this.optionalFields,
    this.networkPolicy,
    required this.dataTtlSeconds,
    required this.requireUserConfirmation,
    required this.consentValidityHours,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      name.hashCode ^
      version.hashCode ^
      pluginApiVersion.hashCode ^
      minAppVersion.hashCode ^
      maxAppVersion.hashCode ^
      description.hashCode ^
      publisher.hashCode ^
      homepage.hashCode ^
      signature.hashCode ^
      requiredFields.hashCode ^
      optionalFields.hashCode ^
      networkPolicy.hashCode ^
      dataTtlSeconds.hashCode ^
      requireUserConfirmation.hashCode ^
      consentValidityHours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginManifest &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          name == other.name &&
          version == other.version &&
          pluginApiVersion == other.pluginApiVersion &&
          minAppVersion == other.minAppVersion &&
          maxAppVersion == other.maxAppVersion &&
          description == other.description &&
          publisher == other.publisher &&
          homepage == other.homepage &&
          signature == other.signature &&
          requiredFields == other.requiredFields &&
          optionalFields == other.optionalFields &&
          networkPolicy == other.networkPolicy &&
          dataTtlSeconds == other.dataTtlSeconds &&
          requireUserConfirmation == other.requireUserConfirmation &&
          consentValidityHours == other.consentValidityHours;
}
