// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'host.dart';
import 'manifest.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_hash`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SandboxState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Module>>
abstract class Module implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Store < SoloHostFunctions >>>
abstract class StoreSoloHostFunctions implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WasmSandbox>>
abstract class WasmSandbox implements RustOpaqueInterface {
  /// Create a store with host functions
  Future<StoreSoloHostFunctions> createStore({
    required SoloHostFunctions hostFunctions,
  });

  static Future<WasmSandbox> default_() =>
      RustLib.instance.api.cratePluginSandboxWasmSandboxDefault();

  /// Load a plugin module with handshake verification
  Future<Module> loadPlugin({
    required List<int> wasmBytes,
    required PluginManifest manifest,
    required Map<String, Map<String, String>> whitelist,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new sandbox
  static Future<WasmSandbox> newInstance() =>
      RustLib.instance.api.cratePluginSandboxWasmSandboxNew();

  /// Terminate the sandbox
  Future<void> terminate();
}
