// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncEngine>>
abstract class SyncEngine implements RustOpaqueInterface {
  /// Download encrypted blob from cloud
  Future<(Uint8List, BigInt)> download();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new sync engine
  static Future<SyncEngine> newInstance({required SyncConfig config}) =>
      RustLib.instance.api.crateSyncEngineSyncEngineNew(config: config);

  /// Get current sequence number
  Future<BigInt> sequence();

  /// Update session token
  Future<void> setSessionToken({required String token});

  /// Get current sync state
  Future<SyncState> state();

  /// Upload encrypted blob to cloud
  Future<SyncResult> upload({required List<int> blob});
}

/// Sync engine configuration
class SyncConfig {
  /// Cloud storage endpoint
  final String endpoint;

  /// Session token
  final String? sessionToken;

  /// Device ID
  final String deviceId;

  const SyncConfig({
    required this.endpoint,
    this.sessionToken,
    required this.deviceId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SyncConfig> newInstance({
    required String endpoint,
    required String deviceId,
  }) => RustLib.instance.api.crateSyncEngineSyncConfigNew(
    endpoint: endpoint,
    deviceId: deviceId,
  );

  @override
  int get hashCode =>
      endpoint.hashCode ^ sessionToken.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConfig &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          sessionToken == other.sessionToken &&
          deviceId == other.deviceId;
}

/// Sync result
class SyncResult {
  final bool success;
  final BigInt newSequence;
  final String? error;

  const SyncResult({
    required this.success,
    required this.newSequence,
    this.error,
  });

  @override
  int get hashCode => success.hashCode ^ newSequence.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          newSequence == other.newSequence &&
          error == other.error;
}

/// Sync state
enum SyncState {
  /// Not synchronized
  idle,

  /// Syncing in progress
  syncing,

  /// In conflict state
  conflict,

  /// Sync error
  error,
}
