// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get the current schema version from sys_config
Future<int> getSchemaVersion({required Connection conn}) =>
    RustLib.instance.api.crateVaultMigrationGetSchemaVersion(conn: conn);

/// Set the schema version in sys_config
Future<void> setSchemaVersion({
  required Connection conn,
  required int version,
}) => RustLib.instance.api.crateVaultMigrationSetSchemaVersion(
  conn: conn,
  version: version,
);

/// Apply a migration atomically within a transaction
Future<void> applyMigration({
  required Connection conn,
  required int version,
  required String sql,
  required String description,
}) => RustLib.instance.api.crateVaultMigrationApplyMigration(
  conn: conn,
  version: version,
  sql: sql,
  description: description,
);

/// Migration v1 -> v2: Add extra_data column to profiles table
Future<void> migrateV1ToV2({required Connection conn}) =>
    RustLib.instance.api.crateVaultMigrationMigrateV1ToV2(conn: conn);

/// Run all pending migrations
Future<void> runMigrations({required Connection conn}) =>
    RustLib.instance.api.crateVaultMigrationRunMigrations(conn: conn);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Connection>>
abstract class Connection implements RustOpaqueInterface {}
