// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../account/manager.dart';
import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base64_decode`, `base64_encode`, `handle_create_profile`, `handle_delete_profile`, `handle_is_unlocked`, `handle_list_profiles`, `handle_load_profile`, `handle_save_profile`, `handle_vault_stats`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CreateProfilePayload`, `JsonProfileSummary`, `SaveProfilePayload`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Handle a vault request and return JSON response
Future<VaultResponse> handleVaultRequest({
  required VaultRequest request,
  required AccountManager accountManager,
}) => RustLib.instance.api.crateVaultProcessorHandleVaultRequest(
  request: request,
  accountManager: accountManager,
);

/// Request envelope for vault operations
class VaultRequest {
  final String action;
  final Value? payload;

  const VaultRequest({required this.action, this.payload});

  @override
  int get hashCode => action.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultRequest &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          payload == other.payload;
}

/// Response envelope for vault operations
class VaultResponse {
  final bool success;
  final Value? data;
  final String? error;

  const VaultResponse({required this.success, this.data, this.error});

  static Future<VaultResponse> error({required String msg}) =>
      RustLib.instance.api.crateVaultProcessorVaultResponseError(msg: msg);

  static Future<VaultResponse> success({required Value data}) =>
      RustLib.instance.api.crateVaultProcessorVaultResponseSuccess(data: data);

  @override
  int get hashCode => success.hashCode ^ data.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultResponse &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          data == other.data &&
          error == other.error;
}
