// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `deserialize_contact_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>
abstract class Profile implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new profile
  static Future<Profile> newInstance({
    required String name,
    required List<int> encryptedData,
  }) => RustLib.instance.api.crateVaultProfileProfileNew(
    name: name,
    encryptedData: encryptedData,
  );

  /// Update profile data
  Future<void> updateData({required List<int> encryptedData});
}

class AddressData {
  final String? label;
  final String? street;
  final String? city;
  final String? state;
  final String? postalCode;
  final String? country;
  final bool isDeleted;
  final DateTime? deletedAt;

  const AddressData({
    this.label,
    this.street,
    this.city,
    this.state,
    this.postalCode,
    this.country,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      street.hashCode ^
      city.hashCode ^
      state.hashCode ^
      postalCode.hashCode ^
      country.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressData &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          street == other.street &&
          city == other.city &&
          state == other.state &&
          postalCode == other.postalCode &&
          country == other.country &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class BankAccountData {
  final String? bankName;
  final String? accountNumber;
  final String? currency;
  final String? swiftBic;
  final String? sortCode;
  final bool isDeleted;
  final DateTime? deletedAt;

  const BankAccountData({
    this.bankName,
    this.accountNumber,
    this.currency,
    this.swiftBic,
    this.sortCode,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      bankName.hashCode ^
      accountNumber.hashCode ^
      currency.hashCode ^
      swiftBic.hashCode ^
      sortCode.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BankAccountData &&
          runtimeType == other.runtimeType &&
          bankName == other.bankName &&
          accountNumber == other.accountNumber &&
          currency == other.currency &&
          swiftBic == other.swiftBic &&
          sortCode == other.sortCode &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class CardData {
  final String? cardNumber;
  final String? cardType;
  final String? expiryDate;
  final String? holderName;
  final String? cvv;
  final bool isDeleted;
  final DateTime? deletedAt;

  const CardData({
    this.cardNumber,
    this.cardType,
    this.expiryDate,
    this.holderName,
    this.cvv,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      cardNumber.hashCode ^
      cardType.hashCode ^
      expiryDate.hashCode ^
      holderName.hashCode ^
      cvv.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardData &&
          runtimeType == other.runtimeType &&
          cardNumber == other.cardNumber &&
          cardType == other.cardType &&
          expiryDate == other.expiryDate &&
          holderName == other.holderName &&
          cvv == other.cvv &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class ContactData {
  final List<ContactEntry> entries;

  const ContactData({required this.entries});

  @override
  int get hashCode => entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactData &&
          runtimeType == other.runtimeType &&
          entries == other.entries;
}

class ContactEntry {
  final String label;
  final String entryType;
  final String value;
  final bool isDeleted;
  final DateTime? deletedAt;

  const ContactEntry({
    required this.label,
    required this.entryType,
    required this.value,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      entryType.hashCode ^
      value.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactEntry &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          entryType == other.entryType &&
          value == other.value &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class EducationData {
  final String? institution;
  final String? degree;
  final String? field;
  final String? startDate;
  final String? endDate;
  final bool isDeleted;
  final DateTime? deletedAt;

  const EducationData({
    this.institution,
    this.degree,
    this.field,
    this.startDate,
    this.endDate,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      institution.hashCode ^
      degree.hashCode ^
      field.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EducationData &&
          runtimeType == other.runtimeType &&
          institution == other.institution &&
          degree == other.degree &&
          field == other.field &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class EmploymentData {
  final String? company;
  final String? position;
  final String? responsibilities;
  final String? startDate;
  final String? endDate;
  final bool isDeleted;
  final DateTime? deletedAt;

  const EmploymentData({
    this.company,
    this.position,
    this.responsibilities,
    this.startDate,
    this.endDate,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      company.hashCode ^
      position.hashCode ^
      responsibilities.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmploymentData &&
          runtimeType == other.runtimeType &&
          company == other.company &&
          position == other.position &&
          responsibilities == other.responsibilities &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class FinancialData {
  final List<BankAccountData> bankAccounts;
  final List<CardData> cards;
  final List<TaxIdData> taxIds;

  const FinancialData({
    required this.bankAccounts,
    required this.cards,
    required this.taxIds,
  });

  @override
  int get hashCode => bankAccounts.hashCode ^ cards.hashCode ^ taxIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FinancialData &&
          runtimeType == other.runtimeType &&
          bankAccounts == other.bankAccounts &&
          cards == other.cards &&
          taxIds == other.taxIds;
}

class IdCardData {
  final String? label;
  final String? number;
  final String? issueDate;
  final String? expiryDate;
  final String? holderName;
  final String? country;
  final bool isDeleted;
  final DateTime? deletedAt;

  const IdCardData({
    this.label,
    this.number,
    this.issueDate,
    this.expiryDate,
    this.holderName,
    this.country,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      number.hashCode ^
      issueDate.hashCode ^
      expiryDate.hashCode ^
      holderName.hashCode ^
      country.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdCardData &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          number == other.number &&
          issueDate == other.issueDate &&
          expiryDate == other.expiryDate &&
          holderName == other.holderName &&
          country == other.country &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class IdentityData {
  final String? fullName;
  final String? givenName;
  final String? familyName;
  final String? dateOfBirth;
  final String? gender;
  final String? nationality;
  final List<IdCardData> idCards;
  final ContactData? contact;
  final List<AddressData> addresses;

  const IdentityData({
    this.fullName,
    this.givenName,
    this.familyName,
    this.dateOfBirth,
    this.gender,
    this.nationality,
    required this.idCards,
    this.contact,
    required this.addresses,
  });

  @override
  int get hashCode =>
      fullName.hashCode ^
      givenName.hashCode ^
      familyName.hashCode ^
      dateOfBirth.hashCode ^
      gender.hashCode ^
      nationality.hashCode ^
      idCards.hashCode ^
      contact.hashCode ^
      addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityData &&
          runtimeType == other.runtimeType &&
          fullName == other.fullName &&
          givenName == other.givenName &&
          familyName == other.familyName &&
          dateOfBirth == other.dateOfBirth &&
          gender == other.gender &&
          nationality == other.nationality &&
          idCards == other.idCards &&
          contact == other.contact &&
          addresses == other.addresses;
}

class LanguageData {
  final String name;
  final String? proficiency;
  final bool isDeleted;
  final DateTime? deletedAt;

  const LanguageData({
    required this.name,
    this.proficiency,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      proficiency.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LanguageData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proficiency == other.proficiency &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class NotificationPreferencesData {
  final bool email;
  final bool sms;
  final bool push;

  const NotificationPreferencesData({
    required this.email,
    required this.sms,
    required this.push,
  });

  @override
  int get hashCode => email.hashCode ^ sms.hashCode ^ push.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationPreferencesData &&
          runtimeType == other.runtimeType &&
          email == other.email &&
          sms == other.sms &&
          push == other.push;
}

class PassportData {
  final String? number;
  final String? country;
  final String? issueDate;
  final String? expiryDate;
  final String? holderName;
  final bool isDeleted;
  final DateTime? deletedAt;

  const PassportData({
    this.number,
    this.country,
    this.issueDate,
    this.expiryDate,
    this.holderName,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      number.hashCode ^
      country.hashCode ^
      issueDate.hashCode ^
      expiryDate.hashCode ^
      holderName.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassportData &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          country == other.country &&
          issueDate == other.issueDate &&
          expiryDate == other.expiryDate &&
          holderName == other.holderName &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class PreferencesData {
  final String? mealPreference;
  final String? seatPreference;
  final String? travelCompanions;
  final NotificationPreferencesData? notificationPreferences;

  const PreferencesData({
    this.mealPreference,
    this.seatPreference,
    this.travelCompanions,
    this.notificationPreferences,
  });

  @override
  int get hashCode =>
      mealPreference.hashCode ^
      seatPreference.hashCode ^
      travelCompanions.hashCode ^
      notificationPreferences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreferencesData &&
          runtimeType == other.runtimeType &&
          mealPreference == other.mealPreference &&
          seatPreference == other.seatPreference &&
          travelCompanions == other.travelCompanions &&
          notificationPreferences == other.notificationPreferences;
}

class ProfessionalData {
  final List<EducationData> education;
  final List<EmploymentData> employment;
  final List<SkillData> skills;
  final List<LanguageData> languages;

  const ProfessionalData({
    required this.education,
    required this.employment,
    required this.skills,
    required this.languages,
  });

  @override
  int get hashCode =>
      education.hashCode ^
      employment.hashCode ^
      skills.hashCode ^
      languages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfessionalData &&
          runtimeType == other.runtimeType &&
          education == other.education &&
          employment == other.employment &&
          skills == other.skills &&
          languages == other.languages;
}

/// Profile stored in vault - wraps encrypted data blob with metadata
class Profile {
  final String id;
  final String name;
  final Uint8List data;
  final DateTime createdAt;
  final DateTime updatedAt;
  final int version;

  const Profile({
    required this.id,
    required this.name,
    required this.data,
    required this.createdAt,
    required this.updatedAt,
    required this.version,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new profile
  static Future<Profile> newInstance({
    required String name,
    required List<int> encryptedData,
  }) => RustLib.instance.api.crateVaultProfileProfileNew(
    name: name,
    encryptedData: encryptedData,
  );

  /// Update profile data
  Future<void> updateData({required List<int> encryptedData}) =>
      RustLib.instance.api.crateVaultProfileProfileUpdateData(
        that: this,
        encryptedData: encryptedData,
      );

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      data.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          data == other.data &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          version == other.version;
}

class ProfileData {
  final IdentityData? identity;
  final TravelData? travel;
  final FinancialData? financial;
  final ProfessionalData? professional;
  final PreferencesData? preferences;

  const ProfileData({
    this.identity,
    this.travel,
    this.financial,
    this.professional,
    this.preferences,
  });

  ProfileData copyWith({
    IdentityData? identity,
    TravelData? travel,
    FinancialData? financial,
    ProfessionalData? professional,
    PreferencesData? preferences,
  }) {
    return ProfileData(
      identity: identity ?? this.identity,
      travel: travel ?? this.travel,
      financial: financial ?? this.financial,
      professional: professional ?? this.professional,
      preferences: preferences ?? this.preferences,
    );
  }

  @override
  int get hashCode =>
      identity.hashCode ^
      travel.hashCode ^
      financial.hashCode ^
      professional.hashCode ^
      preferences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileData &&
          runtimeType == other.runtimeType &&
          identity == other.identity &&
          travel == other.travel &&
          financial == other.financial &&
          professional == other.professional &&
          preferences == other.preferences;
}

/// Profile summary without encrypted data (for listing)
class ProfileSummary {
  final String id;
  final String name;
  final DateTime createdAt;
  final DateTime updatedAt;
  final int version;

  const ProfileSummary({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.updatedAt,
    required this.version,
  });

  /// Create from full profile
  static Future<ProfileSummary> fromProfile({required Profile profile}) =>
      RustLib.instance.api.crateVaultProfileProfileSummaryFromProfile(
        profile: profile,
      );

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          version == other.version;
}

class SkillData {
  final String name;
  final String? level;
  final bool isDeleted;
  final DateTime? deletedAt;

  const SkillData({
    required this.name,
    this.level,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^ level.hashCode ^ isDeleted.hashCode ^ deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          level == other.level &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class TaxIdData {
  final String? taxIdNumber;
  final String? taxIdType;
  final String? issuingAuthority;
  final String? country;
  final bool isDeleted;
  final DateTime? deletedAt;

  const TaxIdData({
    this.taxIdNumber,
    this.taxIdType,
    this.issuingAuthority,
    this.country,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      taxIdNumber.hashCode ^
      taxIdType.hashCode ^
      issuingAuthority.hashCode ^
      country.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaxIdData &&
          runtimeType == other.runtimeType &&
          taxIdNumber == other.taxIdNumber &&
          taxIdType == other.taxIdType &&
          issuingAuthority == other.issuingAuthority &&
          country == other.country &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

class TravelData {
  final List<PassportData> passports;
  final List<VisaData> visas;
  final List<TravelHistoryData> travelHistory;

  const TravelData({
    required this.passports,
    required this.visas,
    required this.travelHistory,
  });

  @override
  int get hashCode =>
      passports.hashCode ^ visas.hashCode ^ travelHistory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TravelData &&
          runtimeType == other.runtimeType &&
          passports == other.passports &&
          visas == other.visas &&
          travelHistory == other.travelHistory;
}

class TravelHistoryData {
  final String destination;
  final String? date;
  final bool isDeleted;
  final DateTime? deletedAt;

  const TravelHistoryData({
    required this.destination,
    this.date,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      destination.hashCode ^
      date.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TravelHistoryData &&
          runtimeType == other.runtimeType &&
          destination == other.destination &&
          date == other.date &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}

/// Wrapper that captures unknown fields for forward compatibility.
/// Uses serde(flatten) to capture any fields not in ProfileData.
class VersionedProfileData {
  final int version;
  final ProfileData data;

  /// Captured unknown fields from future schema versions.
  /// These are preserved but not re-serialized into data fields.
  final Map<String, Value> legacyData;

  const VersionedProfileData({
    required this.version,
    required this.data,
    required this.legacyData,
  });

  /// Deserialize from JSON string, capturing unknown fields
  static Future<VersionedProfileData> deserialize({required String jsonStr}) =>
      RustLib.instance.api.crateVaultProfileVersionedProfileDataDeserialize(
        jsonStr: jsonStr,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new VersionedProfileData with current schema version
  static Future<VersionedProfileData> newInstance({
    required ProfileData data,
  }) =>
      RustLib.instance.api.crateVaultProfileVersionedProfileDataNew(data: data);

  /// Serialize to JSON string
  Future<String> serialize() => RustLib.instance.api
      .crateVaultProfileVersionedProfileDataSerialize(that: this);

  @override
  int get hashCode => version.hashCode ^ data.hashCode ^ legacyData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionedProfileData &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          data == other.data &&
          legacyData == other.legacyData;
}

class VisaData {
  final String? country;
  final String? visaType;
  final String? number;
  final String? issueDate;
  final String? expiryDate;
  final bool isDeleted;
  final DateTime? deletedAt;

  const VisaData({
    this.country,
    this.visaType,
    this.number,
    this.issueDate,
    this.expiryDate,
    required this.isDeleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      country.hashCode ^
      visaType.hashCode ^
      number.hashCode ^
      issueDate.hashCode ^
      expiryDate.hashCode ^
      isDeleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisaData &&
          runtimeType == other.runtimeType &&
          country == other.country &&
          visaType == other.visaType &&
          number == other.number &&
          issueDate == other.issueDate &&
          expiryDate == other.expiryDate &&
          isDeleted == other.isDeleted &&
          deletedAt == other.deletedAt;
}
