// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../vault.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'profile.dart';

// These functions are ignored because they are not marked as `pub`: `hex_encode`, `init_schema`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultStore>>
abstract class VaultStore implements RustOpaqueInterface {
  /// Delete a profile by ID
  Future<void> deleteProfile({required String id});

  /// List all profile summaries
  Future<List<ProfileSummary>> listProfiles();

  /// Load a profile by ID
  Future<Profile?> loadProfile({required String id});

  /// Lock the vault
  Future<void> lock();

  /// Open or create a vault at the given path
  static Future<VaultStore> open({required VaultConfig config}) =>
      RustLib.instance.api.crateVaultStoreVaultStoreOpen(config: config);

  /// Save a profile (INSERT or UPDATE)
  Future<void> saveProfile({required Profile profile});

  /// Get vault state
  Future<VaultState> state();

  /// Get vault statistics
  Future<VaultStats> stats();
}
