// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Encrypt data using AES-256-GCM with a blob format
///
/// Returns: Magic (4) + Version (1) + Nonce (12) + Ciphertext (*) + Tag (16)
Future<ZeroizingVecU8> encryptBlob({
  required U8Array32 key,
  required List<int> plaintext,
}) => RustLib.instance.api.crateCryptoAesEncryptBlob(
  key: key,
  plaintext: plaintext,
);

/// Decrypt data from a blob format
Future<ZeroizingVecU8> decryptBlob({
  required U8Array32 key,
  required List<int> blob,
}) => RustLib.instance.api.crateCryptoAesDecryptBlob(key: key, blob: blob);

/// Low-level FFI encryption function
///
/// # Safety
/// All pointers must be non-null and valid
Future<int> aes256GcmEncrypt({
  required ConstU8 key,
  required ConstU8 plaintext,
  required BigInt plaintextLen,
  required MutU8 nonce,
  required MutU8 ciphertext,
  required MutUsize ciphertextLen,
}) => RustLib.instance.api.crateCryptoAesAes256GcmEncrypt(
  key: key,
  plaintext: plaintext,
  plaintextLen: plaintextLen,
  nonce: nonce,
  ciphertext: ciphertext,
  ciphertextLen: ciphertextLen,
);

/// Low-level FFI decryption function
///
/// # Safety
/// All pointers must be non-null and valid
Future<int> aes256GcmDecrypt({
  required ConstU8 key,
  required ConstU8 ciphertext,
  required BigInt ciphertextLen,
  required ConstU8 nonce,
  required MutU8 plaintext,
  required MutUsize plaintextLen,
}) => RustLib.instance.api.crateCryptoAesAes256GcmDecrypt(
  key: key,
  ciphertext: ciphertext,
  ciphertextLen: ciphertextLen,
  nonce: nonce,
  plaintext: plaintext,
  plaintextLen: plaintextLen,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Zeroizing < Vec < u8 > >>>
abstract class ZeroizingVecU8 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* const u8>>
abstract class ConstU8 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* mut u8>>
abstract class MutU8 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* mut usize>>
abstract class MutUsize implements RustOpaqueInterface {}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}
