// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../account/manager.dart';
import '../frb_generated.dart';
import 'aes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a cryptographically secure random salt
///
/// # Safety
/// * `salt` must point to at least 32 bytes of writable memory
///
/// # Arguments
/// * `salt` - Pointer to output buffer (must be at least 32 bytes)
/// * `len` - Must be 32
///
/// # Returns
/// 0 on success, negative error code on failure
Future<int> argon2GenerateSalt({required MutU8 salt, required BigInt len}) =>
    RustLib.instance.api.crateCryptoArgon2Argon2GenerateSalt(
      salt: salt,
      len: len,
    );

/// Derive a key using Argon2id
///
/// # Safety
/// - All pointer parameters must be non-null and valid
/// - memory_kib must be at least 8 (argon2 minimum)
/// - iterations must be at least 1
/// - output must have at least 32 bytes of space
///
/// # Arguments
/// * `password` - Pointer to password bytes
/// * `password_len` - Length of password
/// * `salt` - Pointer to 32-byte salt
/// * `salt_len` - Must be 32
/// * `memory_kib` - Memory in KiB (e.g., 65536 for 64MB) - MUST BE KiB, NOT KB!
/// * `iterations` - Number of iterations
/// * `parallelism` - Number of parallel threads
/// * `output` - Pointer to output buffer (must be at least 32 bytes)
/// * `output_len` - Must be 32
///
/// # Returns
/// 0 on success, negative error code on failure
Future<int> argon2DeriveKey({
  required ConstU8 password,
  required BigInt passwordLen,
  required ConstU8 salt,
  required BigInt saltLen,
  required int memoryKib,
  required int iterations,
  required int parallelism,
  required MutU8 output,
  required BigInt outputLen,
}) => RustLib.instance.api.crateCryptoArgon2Argon2DeriveKey(
  password: password,
  passwordLen: passwordLen,
  salt: salt,
  saltLen: saltLen,
  memoryKib: memoryKib,
  iterations: iterations,
  parallelism: parallelism,
  output: output,
  outputLen: outputLen,
);

/// High-level Argon2id key derivation function
Future<ZeroizingU832> deriveKey({
  required String password,
  required List<int> salt,
  required int memoryKib,
  required int iterations,
  required int parallelism,
}) => RustLib.instance.api.crateCryptoArgon2DeriveKey(
  password: password,
  salt: salt,
  memoryKib: memoryKib,
  iterations: iterations,
  parallelism: parallelism,
);
