// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate secure random bytes
Future<Uint8List> randomBytes({required BigInt len}) =>
    RustLib.instance.api.crateCryptoUtilsRandomBytes(len: len);

/// Constant-time comparison to prevent timing attacks
Future<bool> constantTimeCompare({
  required List<int> a,
  required List<int> b,
}) => RustLib.instance.api.crateCryptoUtilsConstantTimeCompare(a: a, b: b);
