// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `decrypt_profile_data_bytes`, `encrypt_profile_data_bytes`, `get_session_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DeriveKeyResult`, `FrbKdfPreset`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Initialize the account manager with a base path.
/// Must be called before any other vault operations.
Future<void> frbInitAccountManager({required String basePath}) =>
    RustLib.instance.api.crateApiFrbInitAccountManager(basePath: basePath);

/// Test function — validates FRB can generate a simple function
Future<String> frbPing() => RustLib.instance.api.crateApiFrbPing();

/// Test function — validates FRB handles enum-with-data return
Future<PropertyValue> frbTestPropertyValue() =>
    RustLib.instance.api.crateApiFrbTestPropertyValue();

/// Test function — validates FRB handles nested HashMap
Future<FormHistories> frbTestFormHistories() =>
    RustLib.instance.api.crateApiFrbTestFormHistories();

/// Encrypt arbitrary bytes using the vault's session key.
/// Returns the encrypted SOLO blob bytes.
/// Vault must be unlocked.
Future<Uint8List> frbEncryptBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiFrbEncryptBytes(data: data);

/// Decrypt SOLO blob (or legacy Dart format) bytes using the vault's session key.
/// Returns the plaintext bytes.
/// Vault must be unlocked.
Future<Uint8List> frbDecryptBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiFrbDecryptBytes(data: data);

/// Save a profile (create or update) with raw encrypted bytes.
/// Returns the profile summary on success.
/// Vault must be unlocked.
Future<ProfileSummary> frbSaveProfile({
  required String name,
  required List<int> data,
}) => RustLib.instance.api.crateApiFrbSaveProfile(name: name, data: data);

/// Load a profile by ID, returning raw encrypted bytes.
/// Vault must be unlocked.
Future<LoadedProfile?> frbLoadProfile({required String id}) =>
    RustLib.instance.api.crateApiFrbLoadProfile(id: id);

/// Create a new account. Returns account info including salt and verify_hash.
Future<CreateAccountResult> frbCreateAccount({
  required String name,
  required String password,
}) => RustLib.instance.api.crateApiFrbCreateAccount(
  name: name,
  password: password,
);

/// Unlock the vault with account_id and password.
/// Returns success status and crypto_version.
Future<UnlockVaultResult> frbUnlockVault({
  required String accountId,
  required String password,
}) => RustLib.instance.api.crateApiFrbUnlockVault(
  accountId: accountId,
  password: password,
);

/// Lock the vault — clears session key and closes database connection.
Future<bool> frbLockVault() => RustLib.instance.api.crateApiFrbLockVault();

/// List all accounts.
Future<List<AccountInfo>> frbListAccounts() =>
    RustLib.instance.api.crateApiFrbListAccounts();

/// Delete an account and all its data.
Future<bool> frbDeleteAccount({required String accountId}) =>
    RustLib.instance.api.crateApiFrbDeleteAccount(accountId: accountId);

/// Get vault statistics.
Future<VaultStats> frbGetVaultStats() =>
    RustLib.instance.api.crateApiFrbGetVaultStats();

/// Change account password.
Future<ChangePasswordResult> frbChangePassword({
  required String accountId,
  required String oldPassword,
  required String newPassword,
}) => RustLib.instance.api.crateApiFrbChangePassword(
  accountId: accountId,
  oldPassword: oldPassword,
  newPassword: newPassword,
);

/// Derive a key from password and salt using Argon2id.
/// This is a standalone function that doesn't require vault to be unlocked.
/// Used by Dart auth flow for biometric credential verification, etc.
///
/// - `salt`: raw salt bytes (typically 32 bytes)
/// - `memory_kib`: memory in KiB (e.g. 16384 for 16 MiB)
/// - `iterations`: number of iterations (e.g. 1)
/// - `parallelism`: degree of parallelism (e.g. 4)
Future<Uint8List> frbDeriveKey({
  required String password,
  required List<int> salt,
  required int memoryKib,
  required int iterations,
  required int parallelism,
}) => RustLib.instance.api.crateApiFrbDeriveKey(
  password: password,
  salt: salt,
  memoryKib: memoryKib,
  iterations: iterations,
  parallelism: parallelism,
);

/// Generate cryptographically secure random bytes.
/// Used for salt generation, nonces, and biometric tokens.
Future<Uint8List> frbGenerateSalt({required int length}) =>
    RustLib.instance.api.crateApiFrbGenerateSalt(length: length);

/// Encrypt data with an explicit 32-byte key using AES-256-GCM (SOLO blob format).
/// Does NOT require the vault to be unlocked — the key is provided by the caller.
/// Used by biometric credential service to encrypt session keys and bio tokens.
Future<Uint8List> frbEncryptWithKey({
  required List<int> key,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiFrbEncryptWithKey(
  key: key,
  plaintext: plaintext,
);

/// Decrypt SOLO blob (or legacy format) data with an explicit 32-byte key.
/// Does NOT require the vault to be unlocked — the key is provided by the caller.
/// Used by biometric credential service to decrypt session keys and bio tokens.
Future<Uint8List> frbDecryptWithKey({
  required List<int> key,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiFrbDecryptWithKey(
  key: key,
  ciphertext: ciphertext,
);

/// Constant-time comparison of two byte slices.
/// Prevents timing attacks by always comparing all bytes regardless of early mismatch.
/// Use for comparing hashes, keys, or other cryptographic material.
Future<bool> frbConstantTimeCompare({
  required List<int> a,
  required List<int> b,
}) => RustLib.instance.api.crateApiFrbConstantTimeCompare(a: a, b: b);

/// Discover SoloSoul devices on the local network via mDNS.
/// Returns a list of discovered devices after waiting for [timeout_ms].
Future<List<DiscoveredDevice>> frbMdnsDiscover({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiFrbMdnsDiscover(timeoutMs: timeoutMs);

/// Advertise this device on the local network via mDNS.
/// [device_name] should be unique (e.g. account ID or device name).
/// [port] is the TCP port the sync server listens on.
Future<void> frbMdnsAdvertise({
  required String deviceName,
  required int port,
}) => RustLib.instance.api.crateApiFrbMdnsAdvertise(
  deviceName: deviceName,
  port: port,
);

/// Sync profile with a remote device as the initiator (sends state vector first).
///
/// [account_id] identifies the account to sync.
/// [remote_addr] is the remote device address (e.g. "192.168.1.5:9900").
/// [pairing_key] is the shared pairing key for Noise handshake.
/// [device_salt] is this device's unique identifier for key derivation.
Future<SyncResult> frbSyncInitiator({
  required String accountId,
  required String remoteAddr,
  required List<int> pairingKey,
  required List<int> deviceSalt,
}) => RustLib.instance.api.crateApiFrbSyncInitiator(
  accountId: accountId,
  remoteAddr: remoteAddr,
  pairingKey: pairingKey,
  deviceSalt: deviceSalt,
);

/// Sync profile with a remote device as the responder (receives state vector first).
///
/// [account_id] identifies the account to sync.
/// [remote_addr] is the remote device address (e.g. "192.168.1.5:9900").
/// [pairing_key] is the shared pairing key for Noise handshake.
/// [device_salt] is this device's unique identifier for key derivation.
Future<SyncResult> frbSyncResponder({
  required String accountId,
  required String remoteAddr,
  required List<int> pairingKey,
  required List<int> deviceSalt,
}) => RustLib.instance.api.crateApiFrbSyncResponder(
  accountId: accountId,
  remoteAddr: remoteAddr,
  pairingKey: pairingKey,
  deviceSalt: deviceSalt,
);

/// Phase 1 兼容：仅加载 rec 模型
Future<void> frbOcrInit({required List<int> modelBytes}) =>
    RustLib.instance.api.crateApiFrbOcrInit(modelBytes: modelBytes);

/// Phase 2：加载 det + cls + rec 三个模型
///
/// `det_model_bytes`: det 模型字节（~4MB），空切片表示跳过
/// `cls_model_bytes`: cls 模型字节（~1MB），空切片表示跳过
/// `rec_model_bytes`: rec 模型字节（~8MB）
Future<void> frbOcrInitV2({
  required List<int> detModelBytes,
  required List<int> clsModelBytes,
  required List<int> recModelBytes,
}) => RustLib.instance.api.crateApiFrbOcrInitV2(
  detModelBytes: detModelBytes,
  clsModelBytes: clsModelBytes,
  recModelBytes: recModelBytes,
);

/// Extract raw MRZ lines from an image.
Future<List<String>> frbOcrExtractMrzRaw({required List<int> imageData}) =>
    RustLib.instance.api.crateApiFrbOcrExtractMrzRaw(imageData: imageData);

/// 对任意图像执行通用 OCR 识别
///
/// 返回结构化结果，包含每个文本块的坐标、文本和置信度。
Future<FrbOcrResult> frbOcrRecognize({required List<int> imageData}) =>
    RustLib.instance.api.crateApiFrbOcrRecognize(imageData: imageData);

/// Get the current OCR engine status.
Future<OcrEngineStatus> frbOcrStatus() =>
    RustLib.instance.api.crateApiFrbOcrStatus();

/// Release OCR engine resources.
Future<void> frbOcrRelease() => RustLib.instance.api.crateApiFrbOcrRelease();

/// Account info from Rust vault
@freezed
sealed class AccountInfo with _$AccountInfo {
  const factory AccountInfo({
    required String id,
    required String name,
    String? createdAt,
    String? lastAccessed,
    String? passwordHint,
    String? lastLoginAt,
    String? lastOperationAt,
    String? lastOperationDesc,
  }) = _AccountInfo;
}

/// Result of password change
@freezed
sealed class ChangePasswordResult with _$ChangePasswordResult {
  const factory ChangePasswordResult({
    required bool success,
    String? error,
    String? salt,
    String? verifyHash,
  }) = _ChangePasswordResult;
}

/// Result of account creation
@freezed
sealed class CreateAccountResult with _$CreateAccountResult {
  const factory CreateAccountResult({
    required bool success,
    String? error,
    String? accountId,
    String? name,
    String? salt,
    String? verifyHash,
  }) = _CreateAccountResult;
}

/// Discovered device on the local network
@freezed
sealed class DiscoveredDevice with _$DiscoveredDevice {
  const factory DiscoveredDevice({
    required String name,
    required String host,
    required int port,
    required List<String> addresses,
  }) = _DiscoveredDevice;
}

/// A field history entry
@freezed
sealed class FieldHistoryEntry with _$FieldHistoryEntry {
  const factory FieldHistoryEntry({
    required PropertyValue value,
    required String timestamp,
    String? source,
  }) = _FieldHistoryEntry;
}

/// Nested HashMap structure — tests FRB's handling of complex nested types
@freezed
sealed class FormHistories with _$FormHistories {
  const factory FormHistories({
    required Map<String, Map<String, List<FieldHistoryEntry>>> histories,
  }) = _FormHistories;
}

/// 边界框（相对坐标 0.0~1.0）
@freezed
sealed class FrbBoundingBox with _$FrbBoundingBox {
  const factory FrbBoundingBox({
    required double x,
    required double y,
    required double width,
    required double height,
  }) = _FrbBoundingBox;
}

/// OCR 文本块
@freezed
sealed class FrbOcrBlock with _$FrbOcrBlock {
  const factory FrbOcrBlock({
    required String text,
    required double confidence,
    required FrbBoundingBox bbox,
  }) = _FrbOcrBlock;
}

/// 通用 OCR 识别结果
@freezed
sealed class FrbOcrResult with _$FrbOcrResult {
  const factory FrbOcrResult({
    required String rawText,
    required List<FrbOcrBlock> blocks,
    required double confidence,
  }) = _FrbOcrResult;
}

/// Loaded profile data returned from Rust
@freezed
sealed class LoadedProfile with _$LoadedProfile {
  const factory LoadedProfile({
    required String id,
    required String name,
    required Uint8List data,
    required int version,
  }) = _LoadedProfile;
}

/// OCR 引擎状态
@freezed
sealed class OcrEngineStatus with _$OcrEngineStatus {
  const factory OcrEngineStatus({
    required bool isLoaded,
    required bool detLoaded,
    required bool clsLoaded,
    required bool recLoaded,
    required BigInt uptimeSecs,
  }) = _OcrEngineStatus;
}

/// Profile summary from Rust vault
@freezed
sealed class ProfileSummary with _$ProfileSummary {
  const factory ProfileSummary({
    required String id,
    required String name,
    required String createdAt,
    required String updatedAt,
    required int version,
  }) = _ProfileSummary;
}

@freezed
sealed class PropertyValue with _$PropertyValue {
  const PropertyValue._();

  const factory PropertyValue.text({
    required String text,
    required SensitivityLevel sensitivity,
  }) = PropertyValue_Text;
  const factory PropertyValue.number({required double value}) =
      PropertyValue_Number;
  const factory PropertyValue.boolean({required bool value}) =
      PropertyValue_Boolean;
  const factory PropertyValue.richText({
    required String html,
    required SensitivityLevel sensitivity,
  }) = PropertyValue_RichText;
}

/// Sensitivity level for profile fields
enum SensitivityLevel { public, private, restricted }

/// Direction of sync result
enum SyncDirection {
  /// Local changes pushed to remote
  pushed,

  /// Remote changes pulled to local
  pulled,

  /// Both sides had changes, merged via CRDT
  merged,

  /// No changes on either side
  noChange,
}

/// Result of a sync operation
@freezed
sealed class SyncResult with _$SyncResult {
  const factory SyncResult({
    required bool success,
    required SyncDirection direction,
    required BigInt bytesSent,
    required BigInt bytesReceived,
    String? error,
  }) = _SyncResult;
}

/// Result of vault unlock
@freezed
sealed class UnlockVaultResult with _$UnlockVaultResult {
  const factory UnlockVaultResult({
    required bool success,
    String? error,
    int? cryptoVersion,
  }) = _UnlockVaultResult;
}

/// Vault statistics returned from Rust
@freezed
sealed class VaultStats with _$VaultStats {
  const factory VaultStats({
    required BigInt profileCount,
    required BigInt totalSizeBytes,
    String? lastModified,
    String? accountId,
  }) = _VaultStats;
}
