// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccountInfo`, `ChangePasswordResult`, `CreateAccountResult`, `ProfileSummary`, `UnlockVaultResult`, `VaultStats`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Test function — validates FRB can generate a simple function
Future<String> frbPing() => RustLib.instance.api.crateApiFrbPing();

/// Test function — validates FRB handles enum-with-data return
Future<PropertyValue> frbTestPropertyValue() =>
    RustLib.instance.api.crateApiFrbTestPropertyValue();

/// Test function — validates FRB handles nested HashMap
Future<FormHistories> frbTestFormHistories() =>
    RustLib.instance.api.crateApiFrbTestFormHistories();

/// A field history entry
@freezed
sealed class FieldHistoryEntry with _$FieldHistoryEntry {
  const factory FieldHistoryEntry({
    required PropertyValue value,
    required String timestamp,
    String? source,
  }) = _FieldHistoryEntry;
}

/// Nested HashMap structure — tests FRB's handling of complex nested types
@freezed
sealed class FormHistories with _$FormHistories {
  const factory FormHistories({
    required Map<String, Map<String, List<FieldHistoryEntry>>> histories,
  }) = _FormHistories;
}

@freezed
sealed class PropertyValue with _$PropertyValue {
  const PropertyValue._();

  const factory PropertyValue.text({
    required String text,
    required SensitivityLevel sensitivity,
  }) = PropertyValue_Text;
  const factory PropertyValue.number({required double value}) =
      PropertyValue_Number;
  const factory PropertyValue.boolean({required bool value}) =
      PropertyValue_Boolean;
  const factory PropertyValue.richText({
    required String html,
    required SensitivityLevel sensitivity,
  }) = PropertyValue_RichText;
}

/// Sensitivity level for profile fields
enum SensitivityLevel { public, private, restricted }
