// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1522251367;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'solosoul_core',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ChangePasswordResult> crateApiFrbChangePassword({
    required String accountId,
    required String oldPassword,
    required String newPassword,
  });

  Future<CreateAccountResult> crateApiFrbCreateAccount({
    required String name,
    required String password,
  });

  Future<Uint8List> crateApiFrbDecryptBytes({required List<int> data});

  Future<Uint8List> crateApiFrbDecryptWithKey({
    required List<int> key,
    required List<int> ciphertext,
  });

  Future<bool> crateApiFrbDeleteAccount({required String accountId});

  Future<Uint8List> crateApiFrbDeriveKey({
    required String password,
    required List<int> salt,
    required int memoryKib,
    required int iterations,
    required int parallelism,
  });

  Future<Uint8List> crateApiFrbEncryptBytes({required List<int> data});

  Future<Uint8List> crateApiFrbEncryptWithKey({
    required List<int> key,
    required List<int> plaintext,
  });

  Future<Uint8List> crateApiFrbGenerateSalt({required int length});

  Future<VaultStats> crateApiFrbGetVaultStats();

  Future<void> crateApiFrbInitAccountManager({required String basePath});

  Future<List<AccountInfo>> crateApiFrbListAccounts();

  Future<LoadedProfile?> crateApiFrbLoadProfile({required String id});

  Future<bool> crateApiFrbLockVault();

  Future<String> crateApiFrbPing();

  Future<ProfileSummary> crateApiFrbSaveProfile({
    required String name,
    required List<int> data,
  });

  Future<FormHistories> crateApiFrbTestFormHistories();

  Future<PropertyValue> crateApiFrbTestPropertyValue();

  Future<UnlockVaultResult> crateApiFrbUnlockVault({
    required String accountId,
    required String password,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ChangePasswordResult> crateApiFrbChangePassword({
    required String accountId,
    required String oldPassword,
    required String newPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountId, serializer);
          sse_encode_String(oldPassword, serializer);
          sse_encode_String(newPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_change_password_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbChangePasswordConstMeta,
        argValues: [accountId, oldPassword, newPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbChangePasswordConstMeta => const TaskConstMeta(
    debugName: "frb_change_password",
    argNames: ["accountId", "oldPassword", "newPassword"],
  );

  @override
  Future<CreateAccountResult> crateApiFrbCreateAccount({
    required String name,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_create_account_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbCreateAccountConstMeta,
        argValues: [name, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbCreateAccountConstMeta => const TaskConstMeta(
    debugName: "frb_create_account",
    argNames: ["name", "password"],
  );

  @override
  Future<Uint8List> crateApiFrbDecryptBytes({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbDecryptBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbDecryptBytesConstMeta =>
      const TaskConstMeta(debugName: "frb_decrypt_bytes", argNames: ["data"]);

  @override
  Future<Uint8List> crateApiFrbDecryptWithKey({
    required List<int> key,
    required List<int> ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbDecryptWithKeyConstMeta,
        argValues: [key, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbDecryptWithKeyConstMeta => const TaskConstMeta(
    debugName: "frb_decrypt_with_key",
    argNames: ["key", "ciphertext"],
  );

  @override
  Future<bool> crateApiFrbDeleteAccount({required String accountId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbDeleteAccountConstMeta,
        argValues: [accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbDeleteAccountConstMeta => const TaskConstMeta(
    debugName: "frb_delete_account",
    argNames: ["accountId"],
  );

  @override
  Future<Uint8List> crateApiFrbDeriveKey({
    required String password,
    required List<int> salt,
    required int memoryKib,
    required int iterations,
    required int parallelism,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          sse_encode_u_32(memoryKib, serializer);
          sse_encode_u_32(iterations, serializer);
          sse_encode_u_32(parallelism, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbDeriveKeyConstMeta,
        argValues: [password, salt, memoryKib, iterations, parallelism],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbDeriveKeyConstMeta => const TaskConstMeta(
    debugName: "frb_derive_key",
    argNames: ["password", "salt", "memoryKib", "iterations", "parallelism"],
  );

  @override
  Future<Uint8List> crateApiFrbEncryptBytes({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbEncryptBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbEncryptBytesConstMeta =>
      const TaskConstMeta(debugName: "frb_encrypt_bytes", argNames: ["data"]);

  @override
  Future<Uint8List> crateApiFrbEncryptWithKey({
    required List<int> key,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbEncryptWithKeyConstMeta,
        argValues: [key, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbEncryptWithKeyConstMeta => const TaskConstMeta(
    debugName: "frb_encrypt_with_key",
    argNames: ["key", "plaintext"],
  );

  @override
  Future<Uint8List> crateApiFrbGenerateSalt({required int length}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(length, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbGenerateSaltConstMeta,
        argValues: [length],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbGenerateSaltConstMeta =>
      const TaskConstMeta(debugName: "frb_generate_salt", argNames: ["length"]);

  @override
  Future<VaultStats> crateApiFrbGetVaultStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_stats,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbGetVaultStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbGetVaultStatsConstMeta =>
      const TaskConstMeta(debugName: "frb_get_vault_stats", argNames: []);

  @override
  Future<void> crateApiFrbInitAccountManager({required String basePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbInitAccountManagerConstMeta,
        argValues: [basePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbInitAccountManagerConstMeta =>
      const TaskConstMeta(
        debugName: "frb_init_account_manager",
        argNames: ["basePath"],
      );

  @override
  Future<List<AccountInfo>> crateApiFrbListAccounts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_account_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbListAccountsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbListAccountsConstMeta =>
      const TaskConstMeta(debugName: "frb_list_accounts", argNames: []);

  @override
  Future<LoadedProfile?> crateApiFrbLoadProfile({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_loaded_profile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbLoadProfileConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbLoadProfileConstMeta =>
      const TaskConstMeta(debugName: "frb_load_profile", argNames: ["id"]);

  @override
  Future<bool> crateApiFrbLockVault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbLockVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbLockVaultConstMeta =>
      const TaskConstMeta(debugName: "frb_lock_vault", argNames: []);

  @override
  Future<String> crateApiFrbPing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbPingConstMeta =>
      const TaskConstMeta(debugName: "frb_ping", argNames: []);

  @override
  Future<ProfileSummary> crateApiFrbSaveProfile({
    required String name,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbSaveProfileConstMeta,
        argValues: [name, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbSaveProfileConstMeta => const TaskConstMeta(
    debugName: "frb_save_profile",
    argNames: ["name", "data"],
  );

  @override
  Future<FormHistories> crateApiFrbTestFormHistories() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_form_histories,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbTestFormHistoriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbTestFormHistoriesConstMeta =>
      const TaskConstMeta(debugName: "frb_test_form_histories", argNames: []);

  @override
  Future<PropertyValue> crateApiFrbTestPropertyValue() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_property_value,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbTestPropertyValueConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbTestPropertyValueConstMeta =>
      const TaskConstMeta(debugName: "frb_test_property_value", argNames: []);

  @override
  Future<UnlockVaultResult> crateApiFrbUnlockVault({
    required String accountId,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountId, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unlock_vault_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFrbUnlockVaultConstMeta,
        argValues: [accountId, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbUnlockVaultConstMeta => const TaskConstMeta(
    debugName: "frb_unlock_vault",
    argNames: ["accountId", "password"],
  );

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  dco_decode_Map_String_Map_String_list_field_history_entry_None_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_map_string_list_field_history_entry_none(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Map<String, List<FieldHistoryEntry>>
  dco_decode_Map_String_list_field_history_entry_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_list_field_history_entry(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountInfo dco_decode_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AccountInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      lastAccessed: dco_decode_opt_String(arr[2]),
      passwordHint: dco_decode_opt_String(arr[3]),
      lastLoginAt: dco_decode_opt_String(arr[4]),
      lastOperationAt: dco_decode_opt_String(arr[5]),
      lastOperationDesc: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LoadedProfile dco_decode_box_autoadd_loaded_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_loaded_profile(raw);
  }

  @protected
  ChangePasswordResult dco_decode_change_password_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChangePasswordResult(
      success: dco_decode_bool(arr[0]),
      error: dco_decode_opt_String(arr[1]),
      salt: dco_decode_opt_String(arr[2]),
      verifyHash: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  CreateAccountResult dco_decode_create_account_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CreateAccountResult(
      success: dco_decode_bool(arr[0]),
      error: dco_decode_opt_String(arr[1]),
      accountId: dco_decode_opt_String(arr[2]),
      name: dco_decode_opt_String(arr[3]),
      salt: dco_decode_opt_String(arr[4]),
      verifyHash: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FieldHistoryEntry dco_decode_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FieldHistoryEntry(
      value: dco_decode_property_value(arr[0]),
      timestamp: dco_decode_String(arr[1]),
      source: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  FormHistories dco_decode_form_histories(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FormHistories(
      histories:
          dco_decode_Map_String_Map_String_list_field_history_entry_None_None(
            arr[0],
          ),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AccountInfo> dco_decode_list_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_account_info).toList();
  }

  @protected
  List<FieldHistoryEntry> dco_decode_list_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_field_history_entry).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, List<FieldHistoryEntry>)>
  dco_decode_list_record_string_list_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_list_field_history_entry)
        .toList();
  }

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  dco_decode_list_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_map_string_list_field_history_entry_none)
        .toList();
  }

  @protected
  LoadedProfile dco_decode_loaded_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LoadedProfile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      data: dco_decode_list_prim_u_8_strict(arr[2]),
      version: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  LoadedProfile? dco_decode_opt_box_autoadd_loaded_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_loaded_profile(raw);
  }

  @protected
  ProfileSummary dco_decode_profile_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProfileSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
      updatedAt: dco_decode_String(arr[3]),
      version: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  PropertyValue dco_decode_property_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PropertyValue_Text(
          text: dco_decode_String(raw[1]),
          sensitivity: dco_decode_sensitivity_level(raw[2]),
        );
      case 1:
        return PropertyValue_Number(value: dco_decode_f_64(raw[1]));
      case 2:
        return PropertyValue_Boolean(value: dco_decode_bool(raw[1]));
      case 3:
        return PropertyValue_RichText(
          html: dco_decode_String(raw[1]),
          sensitivity: dco_decode_sensitivity_level(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  (String, List<FieldHistoryEntry>)
  dco_decode_record_string_list_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_list_field_history_entry(arr[1]),
    );
  }

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  dco_decode_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_Map_String_list_field_history_entry_None(arr[1]),
    );
  }

  @protected
  SensitivityLevel dco_decode_sensitivity_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SensitivityLevel.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UnlockVaultResult dco_decode_unlock_vault_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return UnlockVaultResult(
      success: dco_decode_bool(arr[0]),
      error: dco_decode_opt_String(arr[1]),
      cryptoVersion: dco_decode_opt_box_autoadd_i_32(arr[2]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VaultStats dco_decode_vault_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VaultStats(
      profileCount: dco_decode_usize(arr[0]),
      totalSizeBytes: dco_decode_u_64(arr[1]),
      lastModified: dco_decode_opt_String(arr[2]),
      accountId: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  sse_decode_Map_String_Map_String_list_field_history_entry_None_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner =
        sse_decode_list_record_string_map_string_list_field_history_entry_none(
          deserializer,
        );
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Map<String, List<FieldHistoryEntry>>
  sse_decode_Map_String_list_field_history_entry_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_list_field_history_entry(
      deserializer,
    );
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_lastAccessed = sse_decode_opt_String(deserializer);
    var var_passwordHint = sse_decode_opt_String(deserializer);
    var var_lastLoginAt = sse_decode_opt_String(deserializer);
    var var_lastOperationAt = sse_decode_opt_String(deserializer);
    var var_lastOperationDesc = sse_decode_opt_String(deserializer);
    return AccountInfo(
      id: var_id,
      name: var_name,
      lastAccessed: var_lastAccessed,
      passwordHint: var_passwordHint,
      lastLoginAt: var_lastLoginAt,
      lastOperationAt: var_lastOperationAt,
      lastOperationDesc: var_lastOperationDesc,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  LoadedProfile sse_decode_box_autoadd_loaded_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_loaded_profile(deserializer));
  }

  @protected
  ChangePasswordResult sse_decode_change_password_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_salt = sse_decode_opt_String(deserializer);
    var var_verifyHash = sse_decode_opt_String(deserializer);
    return ChangePasswordResult(
      success: var_success,
      error: var_error,
      salt: var_salt,
      verifyHash: var_verifyHash,
    );
  }

  @protected
  CreateAccountResult sse_decode_create_account_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_accountId = sse_decode_opt_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_salt = sse_decode_opt_String(deserializer);
    var var_verifyHash = sse_decode_opt_String(deserializer);
    return CreateAccountResult(
      success: var_success,
      error: var_error,
      accountId: var_accountId,
      name: var_name,
      salt: var_salt,
      verifyHash: var_verifyHash,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FieldHistoryEntry sse_decode_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_property_value(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    var var_source = sse_decode_opt_String(deserializer);
    return FieldHistoryEntry(
      value: var_value,
      timestamp: var_timestamp,
      source: var_source,
    );
  }

  @protected
  FormHistories sse_decode_form_histories(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_histories =
        sse_decode_Map_String_Map_String_list_field_history_entry_None_None(
          deserializer,
        );
    return FormHistories(histories: var_histories);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<AccountInfo> sse_decode_list_account_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AccountInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_account_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<FieldHistoryEntry> sse_decode_list_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FieldHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_field_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, List<FieldHistoryEntry>)>
  sse_decode_list_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, List<FieldHistoryEntry>)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_list_field_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  sse_decode_list_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, Map<String, List<FieldHistoryEntry>>)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_record_string_map_string_list_field_history_entry_none(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  LoadedProfile sse_decode_loaded_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_version = sse_decode_u_32(deserializer);
    return LoadedProfile(
      id: var_id,
      name: var_name,
      data: var_data,
      version: var_version,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LoadedProfile? sse_decode_opt_box_autoadd_loaded_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_loaded_profile(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileSummary sse_decode_profile_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_version = sse_decode_u_32(deserializer);
    return ProfileSummary(
      id: var_id,
      name: var_name,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      version: var_version,
    );
  }

  @protected
  PropertyValue sse_decode_property_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        var var_sensitivity = sse_decode_sensitivity_level(deserializer);
        return PropertyValue_Text(text: var_text, sensitivity: var_sensitivity);
      case 1:
        var var_value = sse_decode_f_64(deserializer);
        return PropertyValue_Number(value: var_value);
      case 2:
        var var_value = sse_decode_bool(deserializer);
        return PropertyValue_Boolean(value: var_value);
      case 3:
        var var_html = sse_decode_String(deserializer);
        var var_sensitivity = sse_decode_sensitivity_level(deserializer);
        return PropertyValue_RichText(
          html: var_html,
          sensitivity: var_sensitivity,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  (String, List<FieldHistoryEntry>)
  sse_decode_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_list_field_history_entry(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  sse_decode_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_Map_String_list_field_history_entry_None(
      deserializer,
    );
    return (var_field0, var_field1);
  }

  @protected
  SensitivityLevel sse_decode_sensitivity_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SensitivityLevel.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UnlockVaultResult sse_decode_unlock_vault_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_cryptoVersion = sse_decode_opt_box_autoadd_i_32(deserializer);
    return UnlockVaultResult(
      success: var_success,
      error: var_error,
      cryptoVersion: var_cryptoVersion,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VaultStats sse_decode_vault_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_profileCount = sse_decode_usize(deserializer);
    var var_totalSizeBytes = sse_decode_u_64(deserializer);
    var var_lastModified = sse_decode_opt_String(deserializer);
    var var_accountId = sse_decode_opt_String(deserializer);
    return VaultStats(
      profileCount: var_profileCount,
      totalSizeBytes: var_totalSizeBytes,
      lastModified: var_lastModified,
      accountId: var_accountId,
    );
  }

  @protected
  void sse_encode_Map_String_Map_String_list_field_history_entry_None_None(
    Map<String, Map<String, List<FieldHistoryEntry>>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_map_string_list_field_history_entry_none(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_list_field_history_entry_None(
    Map<String, List<FieldHistoryEntry>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_list_field_history_entry(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.lastAccessed, serializer);
    sse_encode_opt_String(self.passwordHint, serializer);
    sse_encode_opt_String(self.lastLoginAt, serializer);
    sse_encode_opt_String(self.lastOperationAt, serializer);
    sse_encode_opt_String(self.lastOperationDesc, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_loaded_profile(
    LoadedProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_loaded_profile(self, serializer);
  }

  @protected
  void sse_encode_change_password_result(
    ChangePasswordResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_opt_String(self.salt, serializer);
    sse_encode_opt_String(self.verifyHash, serializer);
  }

  @protected
  void sse_encode_create_account_result(
    CreateAccountResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_opt_String(self.accountId, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.salt, serializer);
    sse_encode_opt_String(self.verifyHash, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_field_history_entry(
    FieldHistoryEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_property_value(self.value, serializer);
    sse_encode_String(self.timestamp, serializer);
    sse_encode_opt_String(self.source, serializer);
  }

  @protected
  void sse_encode_form_histories(FormHistories self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Map_String_Map_String_list_field_history_entry_None_None(
      self.histories,
      serializer,
    );
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_account_info(
    List<AccountInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_account_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_field_history_entry(
    List<FieldHistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_field_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_list_field_history_entry(
    List<(String, List<FieldHistoryEntry>)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_list_field_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_map_string_list_field_history_entry_none(
    List<(String, Map<String, List<FieldHistoryEntry>>)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_map_string_list_field_history_entry_none(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_loaded_profile(LoadedProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_u_32(self.version, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_loaded_profile(
    LoadedProfile? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_loaded_profile(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_u_32(self.version, serializer);
  }

  @protected
  void sse_encode_property_value(PropertyValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PropertyValue_Text(text: final text, sensitivity: final sensitivity):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
        sse_encode_sensitivity_level(sensitivity, serializer);
      case PropertyValue_Number(value: final value):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(value, serializer);
      case PropertyValue_Boolean(value: final value):
        sse_encode_i_32(2, serializer);
        sse_encode_bool(value, serializer);
      case PropertyValue_RichText(
        html: final html,
        sensitivity: final sensitivity,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(html, serializer);
        sse_encode_sensitivity_level(sensitivity, serializer);
    }
  }

  @protected
  void sse_encode_record_string_list_field_history_entry(
    (String, List<FieldHistoryEntry>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_list_field_history_entry(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_map_string_list_field_history_entry_none(
    (String, Map<String, List<FieldHistoryEntry>>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_Map_String_list_field_history_entry_None(self.$2, serializer);
  }

  @protected
  void sse_encode_sensitivity_level(
    SensitivityLevel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_unlock_vault_result(
    UnlockVaultResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_opt_box_autoadd_i_32(self.cryptoVersion, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vault_stats(VaultStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.profileCount, serializer);
    sse_encode_u_64(self.totalSizeBytes, serializer);
    sse_encode_opt_String(self.lastModified, serializer);
    sse_encode_opt_String(self.accountId, serializer);
  }
}
