// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  dco_decode_Map_String_Map_String_list_field_history_entry_None_None(
    dynamic raw,
  );

  @protected
  Map<String, List<FieldHistoryEntry>>
  dco_decode_Map_String_list_field_history_entry_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FieldHistoryEntry dco_decode_field_history_entry(dynamic raw);

  @protected
  FormHistories dco_decode_form_histories(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<FieldHistoryEntry> dco_decode_list_field_history_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, List<FieldHistoryEntry>)>
  dco_decode_list_record_string_list_field_history_entry(dynamic raw);

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  dco_decode_list_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PropertyValue dco_decode_property_value(dynamic raw);

  @protected
  (String, List<FieldHistoryEntry>)
  dco_decode_record_string_list_field_history_entry(dynamic raw);

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  dco_decode_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  );

  @protected
  SensitivityLevel dco_decode_sensitivity_level(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  sse_decode_Map_String_Map_String_list_field_history_entry_None_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, List<FieldHistoryEntry>>
  sse_decode_Map_String_list_field_history_entry_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FieldHistoryEntry sse_decode_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  FormHistories sse_decode_form_histories(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<FieldHistoryEntry> sse_decode_list_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, List<FieldHistoryEntry>)>
  sse_decode_list_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  sse_decode_list_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PropertyValue sse_decode_property_value(SseDeserializer deserializer);

  @protected
  (String, List<FieldHistoryEntry>)
  sse_decode_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  sse_decode_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  );

  @protected
  SensitivityLevel sse_decode_sensitivity_level(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_Map_String_list_field_history_entry_None_None(
    Map<String, Map<String, List<FieldHistoryEntry>>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_list_field_history_entry_None(
    Map<String, List<FieldHistoryEntry>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_field_history_entry(
    FieldHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_form_histories(FormHistories self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_field_history_entry(
    List<FieldHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_field_history_entry(
    List<(String, List<FieldHistoryEntry>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_map_string_list_field_history_entry_none(
    List<(String, Map<String, List<FieldHistoryEntry>>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_property_value(PropertyValue self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_field_history_entry(
    (String, List<FieldHistoryEntry>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_map_string_list_field_history_entry_none(
    (String, Map<String, List<FieldHistoryEntry>>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sensitivity_level(
    SensitivityLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
