// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1652222294;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'solosoul_core',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiFrbPing();

  Future<FormHistories> crateApiFrbTestFormHistories();

  Future<PropertyValue> crateApiFrbTestPropertyValue();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiFrbPing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbPingConstMeta =>
      const TaskConstMeta(debugName: "frb_ping", argNames: []);

  @override
  Future<FormHistories> crateApiFrbTestFormHistories() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_form_histories,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbTestFormHistoriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbTestFormHistoriesConstMeta =>
      const TaskConstMeta(debugName: "frb_test_form_histories", argNames: []);

  @override
  Future<PropertyValue> crateApiFrbTestPropertyValue() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_property_value,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbTestPropertyValueConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbTestPropertyValueConstMeta =>
      const TaskConstMeta(debugName: "frb_test_property_value", argNames: []);

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  dco_decode_Map_String_Map_String_list_field_history_entry_None_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_map_string_list_field_history_entry_none(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Map<String, List<FieldHistoryEntry>>
  dco_decode_Map_String_list_field_history_entry_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_list_field_history_entry(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FieldHistoryEntry dco_decode_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FieldHistoryEntry(
      value: dco_decode_property_value(arr[0]),
      timestamp: dco_decode_String(arr[1]),
      source: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  FormHistories dco_decode_form_histories(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FormHistories(
      histories:
          dco_decode_Map_String_Map_String_list_field_history_entry_None_None(
            arr[0],
          ),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<FieldHistoryEntry> dco_decode_list_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_field_history_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, List<FieldHistoryEntry>)>
  dco_decode_list_record_string_list_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_list_field_history_entry)
        .toList();
  }

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  dco_decode_list_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_map_string_list_field_history_entry_none)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PropertyValue dco_decode_property_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PropertyValue_Text(
          text: dco_decode_String(raw[1]),
          sensitivity: dco_decode_sensitivity_level(raw[2]),
        );
      case 1:
        return PropertyValue_Number(value: dco_decode_f_64(raw[1]));
      case 2:
        return PropertyValue_Boolean(value: dco_decode_bool(raw[1]));
      case 3:
        return PropertyValue_RichText(
          html: dco_decode_String(raw[1]),
          sensitivity: dco_decode_sensitivity_level(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  (String, List<FieldHistoryEntry>)
  dco_decode_record_string_list_field_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_list_field_history_entry(arr[1]),
    );
  }

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  dco_decode_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_Map_String_list_field_history_entry_None(arr[1]),
    );
  }

  @protected
  SensitivityLevel dco_decode_sensitivity_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SensitivityLevel.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  sse_decode_Map_String_Map_String_list_field_history_entry_None_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner =
        sse_decode_list_record_string_map_string_list_field_history_entry_none(
          deserializer,
        );
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Map<String, List<FieldHistoryEntry>>
  sse_decode_Map_String_list_field_history_entry_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_list_field_history_entry(
      deserializer,
    );
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FieldHistoryEntry sse_decode_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_property_value(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    var var_source = sse_decode_opt_String(deserializer);
    return FieldHistoryEntry(
      value: var_value,
      timestamp: var_timestamp,
      source: var_source,
    );
  }

  @protected
  FormHistories sse_decode_form_histories(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_histories =
        sse_decode_Map_String_Map_String_list_field_history_entry_None_None(
          deserializer,
        );
    return FormHistories(histories: var_histories);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<FieldHistoryEntry> sse_decode_list_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FieldHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_field_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, List<FieldHistoryEntry>)>
  sse_decode_list_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, List<FieldHistoryEntry>)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_list_field_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  sse_decode_list_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, Map<String, List<FieldHistoryEntry>>)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_record_string_map_string_list_field_history_entry_none(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PropertyValue sse_decode_property_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        var var_sensitivity = sse_decode_sensitivity_level(deserializer);
        return PropertyValue_Text(text: var_text, sensitivity: var_sensitivity);
      case 1:
        var var_value = sse_decode_f_64(deserializer);
        return PropertyValue_Number(value: var_value);
      case 2:
        var var_value = sse_decode_bool(deserializer);
        return PropertyValue_Boolean(value: var_value);
      case 3:
        var var_html = sse_decode_String(deserializer);
        var var_sensitivity = sse_decode_sensitivity_level(deserializer);
        return PropertyValue_RichText(
          html: var_html,
          sensitivity: var_sensitivity,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  (String, List<FieldHistoryEntry>)
  sse_decode_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_list_field_history_entry(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  sse_decode_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_Map_String_list_field_history_entry_None(
      deserializer,
    );
    return (var_field0, var_field1);
  }

  @protected
  SensitivityLevel sse_decode_sensitivity_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SensitivityLevel.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_Map_String_Map_String_list_field_history_entry_None_None(
    Map<String, Map<String, List<FieldHistoryEntry>>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_map_string_list_field_history_entry_none(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_list_field_history_entry_None(
    Map<String, List<FieldHistoryEntry>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_list_field_history_entry(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_field_history_entry(
    FieldHistoryEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_property_value(self.value, serializer);
    sse_encode_String(self.timestamp, serializer);
    sse_encode_opt_String(self.source, serializer);
  }

  @protected
  void sse_encode_form_histories(FormHistories self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Map_String_Map_String_list_field_history_entry_None_None(
      self.histories,
      serializer,
    );
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_field_history_entry(
    List<FieldHistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_field_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_list_field_history_entry(
    List<(String, List<FieldHistoryEntry>)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_list_field_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_map_string_list_field_history_entry_none(
    List<(String, Map<String, List<FieldHistoryEntry>>)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_map_string_list_field_history_entry_none(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_property_value(PropertyValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PropertyValue_Text(text: final text, sensitivity: final sensitivity):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
        sse_encode_sensitivity_level(sensitivity, serializer);
      case PropertyValue_Number(value: final value):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(value, serializer);
      case PropertyValue_Boolean(value: final value):
        sse_encode_i_32(2, serializer);
        sse_encode_bool(value, serializer);
      case PropertyValue_RichText(
        html: final html,
        sensitivity: final sensitivity,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(html, serializer);
        sse_encode_sensitivity_level(sensitivity, serializer);
    }
  }

  @protected
  void sse_encode_record_string_list_field_history_entry(
    (String, List<FieldHistoryEntry>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_list_field_history_entry(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_map_string_list_field_history_entry_none(
    (String, Map<String, List<FieldHistoryEntry>>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_Map_String_list_field_history_entry_None(self.$2, serializer);
  }

  @protected
  void sse_encode_sensitivity_level(
    SensitivityLevel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
