// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'plugin/manager.dart';
import 'plugin/manifest.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  dco_decode_Map_String_Map_String_list_field_history_entry_None_None(
    dynamic raw,
  );

  @protected
  Map<String, List<FieldHistoryEntry>>
  dco_decode_Map_String_list_field_history_entry_None(dynamic raw);

  @protected
  RustStreamSink<PluginEvent> dco_decode_StreamSink_plugin_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountInfo dco_decode_account_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  LoadedProfile dco_decode_box_autoadd_loaded_profile(dynamic raw);

  @protected
  NetworkPolicy dco_decode_box_autoadd_network_policy(dynamic raw);

  @protected
  ChangePasswordResult dco_decode_change_password_result(dynamic raw);

  @protected
  CreateAccountResult dco_decode_create_account_result(dynamic raw);

  @protected
  DiscoveredDevice dco_decode_discovered_device(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FieldHistoryEntry dco_decode_field_history_entry(dynamic raw);

  @protected
  FormHistories dco_decode_form_histories(dynamic raw);

  @protected
  FrbBoundingBox dco_decode_frb_bounding_box(dynamic raw);

  @protected
  FrbOcrBlock dco_decode_frb_ocr_block(dynamic raw);

  @protected
  FrbOcrResult dco_decode_frb_ocr_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountInfo> dco_decode_list_account_info(dynamic raw);

  @protected
  List<DiscoveredDevice> dco_decode_list_discovered_device(dynamic raw);

  @protected
  List<FieldHistoryEntry> dco_decode_list_field_history_entry(dynamic raw);

  @protected
  List<FrbOcrBlock> dco_decode_list_frb_ocr_block(dynamic raw);

  @protected
  List<PluginSessionInfo> dco_decode_list_plugin_session_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, List<FieldHistoryEntry>)>
  dco_decode_list_record_string_list_field_history_entry(dynamic raw);

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  dco_decode_list_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  );

  @protected
  LoadedProfile dco_decode_loaded_profile(dynamic raw);

  @protected
  NetworkPolicy dco_decode_network_policy(dynamic raw);

  @protected
  OcrEngineStatus dco_decode_ocr_engine_status(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  LoadedProfile? dco_decode_opt_box_autoadd_loaded_profile(dynamic raw);

  @protected
  NetworkPolicy? dco_decode_opt_box_autoadd_network_policy(dynamic raw);

  @protected
  PluginEvent dco_decode_plugin_event(dynamic raw);

  @protected
  PluginManifest dco_decode_plugin_manifest(dynamic raw);

  @protected
  PluginSessionInfo dco_decode_plugin_session_info(dynamic raw);

  @protected
  ProfileSummary dco_decode_profile_summary(dynamic raw);

  @protected
  PropertyValue dco_decode_property_value(dynamic raw);

  @protected
  (String, List<FieldHistoryEntry>)
  dco_decode_record_string_list_field_history_entry(dynamic raw);

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  dco_decode_record_string_map_string_list_field_history_entry_none(
    dynamic raw,
  );

  @protected
  SensitivityLevel dco_decode_sensitivity_level(dynamic raw);

  @protected
  SyncDirection dco_decode_sync_direction(dynamic raw);

  @protected
  SyncResult dco_decode_sync_result(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnlockVaultResult dco_decode_unlock_vault_result(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultStats dco_decode_vault_stats(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, Map<String, List<FieldHistoryEntry>>>
  sse_decode_Map_String_Map_String_list_field_history_entry_None_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, List<FieldHistoryEntry>>
  sse_decode_Map_String_list_field_history_entry_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PluginEvent> sse_decode_StreamSink_plugin_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LoadedProfile sse_decode_box_autoadd_loaded_profile(
    SseDeserializer deserializer,
  );

  @protected
  NetworkPolicy sse_decode_box_autoadd_network_policy(
    SseDeserializer deserializer,
  );

  @protected
  ChangePasswordResult sse_decode_change_password_result(
    SseDeserializer deserializer,
  );

  @protected
  CreateAccountResult sse_decode_create_account_result(
    SseDeserializer deserializer,
  );

  @protected
  DiscoveredDevice sse_decode_discovered_device(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FieldHistoryEntry sse_decode_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  FormHistories sse_decode_form_histories(SseDeserializer deserializer);

  @protected
  FrbBoundingBox sse_decode_frb_bounding_box(SseDeserializer deserializer);

  @protected
  FrbOcrBlock sse_decode_frb_ocr_block(SseDeserializer deserializer);

  @protected
  FrbOcrResult sse_decode_frb_ocr_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountInfo> sse_decode_list_account_info(SseDeserializer deserializer);

  @protected
  List<DiscoveredDevice> sse_decode_list_discovered_device(
    SseDeserializer deserializer,
  );

  @protected
  List<FieldHistoryEntry> sse_decode_list_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbOcrBlock> sse_decode_list_frb_ocr_block(SseDeserializer deserializer);

  @protected
  List<PluginSessionInfo> sse_decode_list_plugin_session_info(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, List<FieldHistoryEntry>)>
  sse_decode_list_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Map<String, List<FieldHistoryEntry>>)>
  sse_decode_list_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  );

  @protected
  LoadedProfile sse_decode_loaded_profile(SseDeserializer deserializer);

  @protected
  NetworkPolicy sse_decode_network_policy(SseDeserializer deserializer);

  @protected
  OcrEngineStatus sse_decode_ocr_engine_status(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LoadedProfile? sse_decode_opt_box_autoadd_loaded_profile(
    SseDeserializer deserializer,
  );

  @protected
  NetworkPolicy? sse_decode_opt_box_autoadd_network_policy(
    SseDeserializer deserializer,
  );

  @protected
  PluginEvent sse_decode_plugin_event(SseDeserializer deserializer);

  @protected
  PluginManifest sse_decode_plugin_manifest(SseDeserializer deserializer);

  @protected
  PluginSessionInfo sse_decode_plugin_session_info(
    SseDeserializer deserializer,
  );

  @protected
  ProfileSummary sse_decode_profile_summary(SseDeserializer deserializer);

  @protected
  PropertyValue sse_decode_property_value(SseDeserializer deserializer);

  @protected
  (String, List<FieldHistoryEntry>)
  sse_decode_record_string_list_field_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  (String, Map<String, List<FieldHistoryEntry>>)
  sse_decode_record_string_map_string_list_field_history_entry_none(
    SseDeserializer deserializer,
  );

  @protected
  SensitivityLevel sse_decode_sensitivity_level(SseDeserializer deserializer);

  @protected
  SyncDirection sse_decode_sync_direction(SseDeserializer deserializer);

  @protected
  SyncResult sse_decode_sync_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnlockVaultResult sse_decode_unlock_vault_result(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultStats sse_decode_vault_stats(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_Map_String_list_field_history_entry_None_None(
    Map<String, Map<String, List<FieldHistoryEntry>>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_list_field_history_entry_None(
    Map<String, List<FieldHistoryEntry>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_plugin_event_Sse(
    RustStreamSink<PluginEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_loaded_profile(
    LoadedProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_policy(
    NetworkPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_change_password_result(
    ChangePasswordResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_account_result(
    CreateAccountResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovered_device(
    DiscoveredDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_field_history_entry(
    FieldHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_form_histories(FormHistories self, SseSerializer serializer);

  @protected
  void sse_encode_frb_bounding_box(
    FrbBoundingBox self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_ocr_block(FrbOcrBlock self, SseSerializer serializer);

  @protected
  void sse_encode_frb_ocr_result(FrbOcrResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_info(
    List<AccountInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_discovered_device(
    List<DiscoveredDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_history_entry(
    List<FieldHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_ocr_block(
    List<FrbOcrBlock> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_plugin_session_info(
    List<PluginSessionInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_field_history_entry(
    List<(String, List<FieldHistoryEntry>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_map_string_list_field_history_entry_none(
    List<(String, Map<String, List<FieldHistoryEntry>>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_loaded_profile(LoadedProfile self, SseSerializer serializer);

  @protected
  void sse_encode_network_policy(NetworkPolicy self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_engine_status(
    OcrEngineStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_loaded_profile(
    LoadedProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_network_policy(
    NetworkPolicy? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_plugin_event(PluginEvent self, SseSerializer serializer);

  @protected
  void sse_encode_plugin_manifest(
    PluginManifest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_plugin_session_info(
    PluginSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_property_value(PropertyValue self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_field_history_entry(
    (String, List<FieldHistoryEntry>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_map_string_list_field_history_entry_none(
    (String, Map<String, List<FieldHistoryEntry>>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sensitivity_level(
    SensitivityLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_direction(SyncDirection self, SseSerializer serializer);

  @protected
  void sse_encode_sync_result(SyncResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unlock_vault_result(
    UnlockVaultResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_stats(VaultStats self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
