// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_account_manager`, `init_account_manager`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ACCOUNT_MANAGER`, `CoreError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `deref`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `free_rust_string_ffi`, `init_account_manager_ffi`, `vault_request_ffi`

/// Initialize the account manager with base path
Future<bool> initAccountManagerAsync({required String basePath}) =>
    RustLib.instance.api.crateInitAccountManagerAsync(basePath: basePath);

/// Initialize vault with master password
Future<UnlockResult> initVault({
  required String accountName,
  required String password,
  required String basePath,
}) => RustLib.instance.api.crateInitVault(
  accountName: accountName,
  password: password,
  basePath: basePath,
);

/// Unlock vault with master password
Future<UnlockResult> unlockVault({
  required String accountId,
  required String password,
  required String basePath,
}) => RustLib.instance.api.crateUnlockVault(
  accountId: accountId,
  password: password,
  basePath: basePath,
);

/// Lock the vault
Future<bool> lockVault() => RustLib.instance.api.crateLockVault();

/// Check if vault is unlocked
Future<bool> isVaultUnlocked() => RustLib.instance.api.crateIsVaultUnlocked();

/// List all accounts
Future<List<BridgeAccountInfo>> listAccounts({required String basePath}) =>
    RustLib.instance.api.crateListAccounts(basePath: basePath);

/// Get vault statistics
Future<FfiVaultStats> getVaultStats() =>
    RustLib.instance.api.crateGetVaultStats();

/// List all profiles
Future<List<BridgeProfileSummary>> listProfiles() =>
    RustLib.instance.api.crateListProfiles();

/// Create a new profile
Future<BridgeProfileSummary> createProfile({
  required String name,
  required List<int> data,
}) => RustLib.instance.api.crateCreateProfile(name: name, data: data);

/// Save a profile (update if exists)
Future<BridgeProfileSummary> realSaveProfile({
  required String name,
  required List<int> data,
}) => RustLib.instance.api.crateRealSaveProfile(name: name, data: data);

/// Load a profile by ID
Future<Uint8List?> realLoadProfile({required String id}) =>
    RustLib.instance.api.crateRealLoadProfile(id: id);

/// Delete a profile by ID
Future<bool> realDeleteProfile({required String id}) =>
    RustLib.instance.api.crateRealDeleteProfile(id: id);

/// List all profile summaries (FFI version)
Future<List<BridgeProfileSummary>> realListProfiles() =>
    RustLib.instance.api.crateRealListProfiles();

/// Encrypt data with AES-256-GCM
Future<Uint8List> encryptData({
  required List<int> data,
  required List<int> key,
}) => RustLib.instance.api.crateEncryptData(data: data, key: key);

/// Decrypt data with AES-256-GCM
Future<Uint8List> decryptData({
  required List<int> encrypted,
  required List<int> key,
}) => RustLib.instance.api.crateDecryptData(encrypted: encrypted, key: key);

/// Simple ping test function
Future<String> ping({required String s}) =>
    RustLib.instance.api.cratePing(s: s);

/// Unified vault request handler using JSON relay pattern.
///
/// This function sidesteps flutter_rust_bridge's complex type limitations by
/// accepting a JSON request envelope and returning a JSON response envelope.
///
/// Request format:
///   {"action": "list_profiles"|"save_profile"|"create_profile"|"load_profile"|"delete_profile"|"get_vault_stats"|"is_unlocked", "payload": {...}}
///
/// Response format:
///   {"success": bool, "data": {...}, "error": "string"|null}
Future<String> vaultRequest({required String requestJson}) =>
    RustLib.instance.api.crateVaultRequest(requestJson: requestJson);

/// Check if vault is unlocked (C-compatible)
Future<CInt> isVaultUnlockedFfi() =>
    RustLib.instance.api.crateIsVaultUnlockedFfi();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PathBuf>>
abstract class PathBuf implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Value>>
abstract class Value implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< c_int>>
abstract class CInt implements RustOpaqueInterface {}

/// Bridge-specific account info with String dates for Dart
class BridgeAccountInfo {
  final String id;
  final String name;
  final String? lastAccessed;

  const BridgeAccountInfo({
    required this.id,
    required this.name,
    this.lastAccessed,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ lastAccessed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAccountInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          lastAccessed == other.lastAccessed;
}

/// Bridge-specific profile summary with String dates for Dart
class BridgeProfileSummary {
  final String id;
  final String name;
  final String createdAt;
  final String updatedAt;
  final int version;

  const BridgeProfileSummary({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.updatedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProfileSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          version == other.version;
}

/// Vault statistics for FFI bridge
class FfiVaultStats {
  final BigInt profileCount;
  final BigInt totalSizeBytes;
  final String? lastModified;

  const FfiVaultStats({
    required this.profileCount,
    required this.totalSizeBytes,
    this.lastModified,
  });

  @override
  int get hashCode =>
      profileCount.hashCode ^ totalSizeBytes.hashCode ^ lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiVaultStats &&
          runtimeType == other.runtimeType &&
          profileCount == other.profileCount &&
          totalSizeBytes == other.totalSizeBytes &&
          lastModified == other.lastModified;
}

/// Unlock result for Flutter
class UnlockResult {
  final bool success;
  final String? error;

  const UnlockResult({required this.success, this.error});

  @override
  int get hashCode => success.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnlockResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error;
}
