// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultConfig>>
abstract class VaultConfig implements RustOpaqueInterface {
  String get accountId;

  PathBuf get path;

  Uint8List? get sqlcipherKey;

  set accountId(String accountId);

  set path(PathBuf path);

  set sqlcipherKey(Uint8List? sqlcipherKey);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create new vault configuration
  static Future<VaultConfig> newInstance({
    required String accountId,
    required PathBuf path,
  }) => RustLib.instance.api.crateVaultVaultConfigNew(
    accountId: accountId,
    path: path,
  );
}

/// Vault state
enum VaultState {
  /// Vault is locked
  locked,

  /// Vault is unlocked
  unlocked,

  /// Vault is corrupted
  corrupted,
}

/// Vault statistics
class VaultStats {
  final BigInt profileCount;
  final BigInt totalSizeBytes;
  final String? lastModified;

  const VaultStats({
    required this.profileCount,
    required this.totalSizeBytes,
    this.lastModified,
  });

  @override
  int get hashCode =>
      profileCount.hashCode ^ totalSizeBytes.hashCode ^ lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStats &&
          runtimeType == other.runtimeType &&
          profileCount == other.profileCount &&
          totalSizeBytes == other.totalSizeBytes &&
          lastModified == other.lastModified;
}
