//! TUI 屏幕组件。

pub mod about;
pub mod account_list;
pub mod attachment_list;
pub mod backup_list;
pub mod doctor;
pub mod edit_object;
pub mod help;
pub mod history_list;
pub mod home;
pub mod locked;
pub mod new_object;
pub mod object_detail;
pub mod object_list;
pub mod onboarding;
pub mod operation_log;
pub mod search_results;
pub mod size;
pub mod trash_list;
pub mod unlock;
pub mod welcome;
