// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_dir`, `base64_decode`, `base64_encode`, `derive_sqlcipher_key`, `load_accounts_cache`, `save_accounts_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccountConfig`, `AccountMetadata`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AccountManager>>
abstract class AccountManager implements RustOpaqueInterface {
  /// Get the base path
  Future<void> basePath();

  /// Create a new account
  Future<AccountInfo> createAccount({
    required String name,
    required String password,
  });

  /// Get session key (only available when unlocked)
  Future<ZeroizingU832?> getSessionKey();

  /// Get current unlocked account ID
  Future<String?> getUnlockedAccount();

  /// Get vault store reference (only available when unlocked)
  Future<RwLockReadGuardOptionVaultStore?> getVaultStore();

  /// Check if an account name is available
  Future<bool> isNameAvailable({required String name});

  /// Check if vault is unlocked
  Future<bool> isUnlocked();

  /// List all accounts
  Future<List<AccountInfo>> listAccounts();

  /// List accounts sorted by most recent access
  Future<List<AccountInfo>> listAccountsSorted();

  /// Lock the vault
  Future<void> lock();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create or get the account manager singleton
  static Future<AccountManager> newInstance({required PathBuf basePath}) =>
      RustLib.instance.api.crateAccountManagerAccountManagerNew(
        basePath: basePath,
      );

  /// Unlock account with password
  Future<VerifyResult> unlock({
    required String accountId,
    required String password,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< RwLockReadGuard < 'static, Option < VaultStore > >>>
abstract class RwLockReadGuardOptionVaultStore implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Zeroizing < [u8 ; 32] >>>
abstract class ZeroizingU832 implements RustOpaqueInterface {}

/// Account info returned to Flutter
class AccountInfo {
  final String id;
  final String name;
  final DateTime? lastAccessed;

  const AccountInfo({required this.id, required this.name, this.lastAccessed});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ lastAccessed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          lastAccessed == other.lastAccessed;
}

/// Verification result
class VerifyResult {
  final bool success;
  final String? error;

  const VerifyResult({required this.success, this.error});

  @override
  int get hashCode => success.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error;
}
