// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Account info returned to Flutter
class AccountInfo {
  final String id;
  final String name;
  final String salt;
  final String verifyHash;
  final int cryptoVersion;
  final String? lastAccessed;
  final String? passwordHint;
  final String? lastLoginAt;
  final String? lastOperationAt;
  final String? lastOperationDesc;
  final List<DeviceEntry> recentDevices;
  final bool biometricEnabled;

  const AccountInfo({
    required this.id,
    required this.name,
    required this.salt,
    required this.verifyHash,
    required this.cryptoVersion,
    this.lastAccessed,
    this.passwordHint,
    this.lastLoginAt,
    this.lastOperationAt,
    this.lastOperationDesc,
    required this.recentDevices,
    required this.biometricEnabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      salt.hashCode ^
      verifyHash.hashCode ^
      cryptoVersion.hashCode ^
      lastAccessed.hashCode ^
      passwordHint.hashCode ^
      lastLoginAt.hashCode ^
      lastOperationAt.hashCode ^
      lastOperationDesc.hashCode ^
      recentDevices.hashCode ^
      biometricEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          salt == other.salt &&
          verifyHash == other.verifyHash &&
          cryptoVersion == other.cryptoVersion &&
          lastAccessed == other.lastAccessed &&
          passwordHint == other.passwordHint &&
          lastLoginAt == other.lastLoginAt &&
          lastOperationAt == other.lastOperationAt &&
          lastOperationDesc == other.lastOperationDesc &&
          recentDevices == other.recentDevices &&
          biometricEnabled == other.biometricEnabled;
}

/// Device entry for recent devices tracking
class DeviceEntry {
  final String deviceName;
  final String lastUsed;

  const DeviceEntry({required this.deviceName, required this.lastUsed});

  @override
  int get hashCode => deviceName.hashCode ^ lastUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceEntry &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          lastUsed == other.lastUsed;
}
